Feat/add opportunity
twentyhq/twenty pull request #1267
Opened 2023-08-18 13:34 UTC by lucasbordeau

- Added a dropdown button in opportunities page header to create a company
- Refactored WithTopBarContainer into multiple page layout components
- Refactored DropdownButton into a generic component

2023-08-21 13:11 UTC, thaisguigon requested changes

2023-08-21 13:11 UTC, thaisguigon commented on front/src/pages/opportunities/Opportunities.tsx
> +import { IconTargetArrow } from '@tabler/icons-react';
```suggestion
import { IconTargetArrow } from '@/ui/icon';
```

2023-08-23 16:23 UTC, charlesBochet commented on front/src/modules/companies/components/CompanyProgressPicker.tsx
> +import { IconChevronDown } from '@tabler/icons-react';
@Weiko Another good linter rule candidate!

2023-08-23 16:28 UTC, charlesBochet commented on front/src/modules/pipeline/components/PipelineAddButton.tsx
> +  }
I think we can even pass closeDropdownButton directly in the prop

2023-08-23 16:31 UTC, charlesBochet approved these changes

2023-08-23 16:57 UTC, merged