Add Sentry for Backend
twentyhq/twenty pull request #1403
Opened 2023-09-01 09:34 UTC by brendanlaschke

Added Sentry (optional) to the backend. Only used if the env Variable is set ...

2023-09-04 09:46 UTC, magrinj requested changes

2023-09-04 09:46 UTC, magrinj commented on server/.env.example
> +# SENTRY_URL=https://xxx@xxx.ingest.sentry.io/xxx
@brendanlaschke Instead of `SENTRY_URL` I think it's better to name it `SENTRY_DSN`, same name as Sentry use is his own library

2023-09-04 09:46 UTC, magrinj commented on server/src/filters/sentry.filter.ts
> +export class SentryFilter extends BaseExceptionFilter {
@brendanlaschke Should be enough for now, but as @charlesBochet said, when we'll tackle this as a drive other features should be added like the ones in this library: https://github.com/ntegral/nestjs-sentry

2023-09-05 08:19 UTC, charlesBochet commented
Let's actually integrate it properly as a driver! @brendanlaschke could you take inspiration from server/src/integrations/file-storage to create a server/src/integrations/logger 

The idea is to provide different drivers:
- sentryLogger
- consoleLogger

Both of them should implement the same interface. This interface will make it easy to integrate other loggers later without touching its usage.
We should introduce a LOGGER_DRIVER env variable that should support 'console' and 'sentry' as values

2023-09-05 21:07 UTC, brendanlaschke commented
As im new to nestjs I would like to know if im on the right path... 

The driver now logs either to:
- The console via the default logger
- Sentry via the sentry logger

This new logger is registered as the default logger in main.ts and has the type of the default logger for now.

Is something missing or should be changed?

2023-09-11 13:39 UTC, magrinj approved these changes
@brendanlaschke Great job ! 🎉

2023-09-11 19:22 UTC, charlesBochet commented
Merging it!

2023-09-11 19:22 UTC, merged

2023-09-11 22:03 UTC, charlesBochet commented
@brendanlaschke I've made this follow up PR:
- add validation
- add log level support
- use captureMessage instead of addBreadcrump in Sentry sdk api (addBreadCrumb was not working for me)

I've tested that execeptions and logs are flowing to sentry, it works!