Do not hard code PORT
twentyhq/twenty pull request #1465
Opened 2023-09-05 21:45 UTC by OriPekelman

It is better practice not to hard-code the port on which a server is running but rather read it from the environment. It is a requirement for some PaaS services.
The PR should not change current behavior as it will default to 3000 when the environment variable is missing.

2023-09-06 06:22 UTC, magrinj requested changes
@OriPekelman LGTM, thanks for your PR ! Few changes required :)

2023-09-06 06:22 UTC, magrinj commented on server/src/main.ts
> +  await app.listen(process.env.PORT || 3000);
I rather use the `EnvironmentService` here instead, and add `PORT` in the `environment.validation.ts`

2023-09-07 20:47 UTC, charlesBochet reviewed
Thanks for the suggestion @OriPekelman. We should integrate using our .env and our environmentService

2023-09-10 00:51 UTC, charlesBochet commented
I have created https://github.com/twentyhq/twenty/pull/1527 to take care of this issue. Closing this PR, thanks!

2023-09-10 00:51 UTC, closed without merging