fix: Update company picker keyboard navigation
twentyhq/twenty pull request #1628
Opened 2023-09-17 04:42 UTC by G3root

2023-09-17 04:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/twentyhq/twenty?pullRequest=1628) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/twentyhq/twenty?pullRequest=1628) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/twentyhq/twenty?pullRequest=1628) it.</sub>

2023-09-18 15:36 UTC, lucasbordeau requested changes

2023-09-19 01:45 UTC, G3root commented
@lucasbordeau pushed some fixes for the requested changes

2023-09-19 10:09 UTC, lucasbordeau requested changes
It won't work with this current implementation. You need to think with Recoil.

Things to avoid in your implementation : 
- Direct DOM manipulation with classes
- Drilling down refs
- Trying to solve this problem without using Recoil

Create as many atoms as you need so that each component is independent from the other and only uses atoms to compute whether it is hovered or not.

Hint of a solution with Recoil : 
- Create an atom hoverableIds that olds an array of string
- In SingleEntitySelect, or another place where you get the entities, fill this atom with the entity ids, and if there is an onCreateHandler passed, add a last "create-button" id in this array
- Create a currentlyHoveredId atom
- In SingleEntitySelect, in up and down hotkey callback, instead of incrementing a hoverIndex, go to the next id in the array and set currentlyHoveredId to this id, if it's the last go to "create-button" id
- Create a new component PickerCreateButton, that wraps MenuItem, and that calls currentlyHoveredId to know if it's being hovered. This component should expose and onClick event that takes the handleCreate callback

It's a bit more work but you'll get how we use Recoil in our codebase. Keep it up.

2023-09-19 17:27 UTC, G3root commented
hi @lucasbordeau pushed some fixes for the requested changes. This is my first experience with Recoil, so I'm not entirely familiar with how Recoil is utilized here . happy to have some feedback on this 🙏🏼

2023-09-20 09:40 UTC, lucasbordeau requested changes
Great work, I left a few comments for clean code

2023-09-20 09:40 UTC, lucasbordeau commented on front/src/modules/ui/input/relation-picker/components/SingleEntitySelectBase.tsx
> +          (val) => val.id === hoveredId,
Always try to keep a clear naming even for small parts of the code, here it should be at least `entity`

2023-09-20 09:40 UTC, lucasbordeau commented on front/src/modules/ui/input/relation-picker/hooks/useEntitySelectScroll.ts
> +  hoverIds,
`hoveredIds`

2023-09-20 09:40 UTC, lucasbordeau commented on front/src/modules/ui/input/relation-picker/states/relationPickerHoverIdScopedState.ts
> +export const relationPickerHoverIdScopedState = atomFamily<string, string>({
`relationPickerHoveredIdScopedState`

2023-09-20 09:40 UTC, lucasbordeau commented on front/src/modules/ui/input/relation-picker/hooks/useEntitySelectScroll.ts
> +      const nextId = hoverIds[nextIndex];
Please always try to keep a maximum of context in your variable naming, avoid generic names and also shortened names.

Here it should be at something like `nextHoverableId` to tell that we're using this variable for guessing what will be the next item in the list.

2023-09-20 09:40 UTC, lucasbordeau commented on front/src/modules/ui/input/relation-picker/states/recoil-scope-contexts/RelationPickerRecoilScopeContext.ts
> +  'relationship-context',
`relation-picker-context`

2023-09-20 09:40 UTC, lucasbordeau commented on front/src/modules/ui/input/relation-picker/hooks/useEntitySelectScroll.ts
> +  const getIndex = hoverIds.findIndex((val) => val === relationPickerHoverId);
You can put this in a selector, see : https://recoiljs.org/docs/api-reference/utils/selectorFamily And you have an example here : `numberOfTableColumnsScopedSelector`

2023-09-20 09:40 UTC, lucasbordeau commented on front/src/modules/ui/input/relation-picker/hooks/useEntitySelectScroll.ts
> +  const getIndex = hoverIds.findIndex((val) => val === relationPickerHoverId);
If it's too complicated with a selector, try to create a util function at least to abstract this away.

2023-09-21 06:39 UTC, FelixMalfait commented
This is for #909 right? Linking the issue to make sure we close it after this PR is merged

2023-09-21 19:32 UTC, charlesBochet reviewed
Made a few modifications @G3root @lucasbordeau

2023-09-21 19:32 UTC, charlesBochet commented on front/src/modules/ui/input/relation-picker/components/CreateNewButton.tsx
> +export const CreateNewButton = StyledCreateNewButton;
@G3root exporting it as CreateNewButton to hide the fact that this is only a Styled component. The outside world shouldn't care about it!

2023-09-21 19:32 UTC, charlesBochet commented on front/src/modules/ui/input/relation-picker/components/SingleEntitySelect.tsx
> -      {showCreateButton && (
moving it withing SingleSelectBase to simplify the code

2023-09-21 19:32 UTC, charlesBochet commented on front/src/modules/ui/input/relation-picker/components/SingleEntitySelectBase.tsx
> +      EmptyButtonId,
adding EmptyButton possibility

2023-09-21 19:32 UTC, charlesBochet commented on front/src/modules/ui/input/relation-picker/hooks/useEntitySelectScroll.ts
> +  selectableOptionIds,
renaming hoveredId to selectableOptionIds

2023-09-21 19:32 UTC, charlesBochet commented on front/src/modules/ui/input/relation-picker/hooks/useEntitySelectScroll.ts
> +    preselectedOptionId: relationPickerHoveredId,
and this one to preselectedOptionId which is more accurate!

2023-09-21 19:53 UTC, merged