Create consistent ui/input and ui/display for Cell and Fields type : …
twentyhq/twenty pull request #1658
Opened 2023-09-19 15:48 UTC by gitstart-twenty

Fixes #1562

2023-09-19 15:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/twentyhq/twenty?pullRequest=1658) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/twentyhq/twenty?pullRequest=1658) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/twentyhq/twenty?pullRequest=1658) it.</sub>

2023-09-20 09:51 UTC, lucasbordeau commented
This PR should implement : 

- `ui/input/components/ProbabilityInput` (no content-display counter part, see BooleanInput.tsx)
- `ui/input/components/DoubleTextInput`
- `ui/input/components/DoubleTextChipInput`
- `ui/content-display/components/DoubleTextDisplay`
- `ui/content-display/components/DoubleTextChipDisplay`

Those components should be the unique way to input and display those types in table cell and editable fields. (Except for People page title, which is a specific component)

2023-09-21 07:53 UTC, gitstart-twenty commented
> This PR should implement :
> 
> * `ui/input/components/ProbabilityInput` (no content-display counter part, see BooleanInput.tsx)
> * `ui/input/components/DoubleTextInput`
> * `ui/input/components/DoubleTextChipInput`
> * `ui/content-display/components/DoubleTextDisplay`
> * `ui/content-display/components/DoubleTextChipDisplay`
> 
> Those components should be the unique way to input and display those types in table cell and editable fields. (Except for People page title, which is a specific component)

Thanks for the clarification @lucasbordeau

2023-09-21 08:42 UTC, gitstart-twenty commented
Hey @lucasbordeau,
Are the new changes more aligned towards the end goal for the task?

2023-09-22 06:53 UTC, charlesBochet commented
@lucasbordeau whenever you can take a look :)

2023-09-22 09:38 UTC, lucasbordeau requested changes

2023-09-23 06:23 UTC, gitstart-twenty commented on front/src/modules/ui/content-display/components/DoubleTextChipDisplay.tsx
> +        `Unknown relation type: "${entityType}" in GenericEditableDoubleTextChipCellDisplayMode`,
Hey @lucasbordeau,
The above comments have been addressed.

2023-09-25 09:10 UTC, lucasbordeau approved these changes

2023-09-25 09:10 UTC, merged