Add event listener for Escape key to close TableColumnDropdownMenu
twentyhq/twenty pull request #1729
Opened 2023-09-25 17:14 UTC by Parvezkhan0

fixes #1727
## Description

This pull request addresses issue #1727.

### Changes Made

- Added an event listener for the Escape key in the TableColumnDropdownMenu component.
- When the Escape key is pressed, the dropdown menu will now close.

### Testing

- Tested the new functionality to ensure that the dropdown menu closes when the Escape key is pressed.

2023-09-25 17:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/twentyhq/twenty?pullRequest=1729) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/twentyhq/twenty?pullRequest=1729) before we can accept your contribution.<br/><hr/>**Parvez Khan** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/twentyhq/twenty?pullRequest=1729) it.</sub>

2023-09-26 09:02 UTC, Davidkramer1999 commented
The initial approach of using useEffect to add an event listener to the document is not necessarily bad, but it might not be optimal for all scenarios. Using useEffect with an empty dependency array ensures the event listener is only added once when the component mounts and removed when it unmounts. However, since the event listener is global, it could potentially interfere with other parts of the application. A more localized and potentially safer approach would be to add the event listener directly to the element that needs it. This can be easily done in React using the onKeyDown prop like this
<div onKeyDown={handleEscapeKey}>
  {/* Your dropdown content here */}
</div>

2023-09-26 09:16 UTC, thaisguigon requested changes

2023-09-26 09:16 UTC, thaisguigon commented on front/src/modules/ui/table/components/TableColumnDropdownMenu.tsx
> +  }, []);
Hi @Parvezkhan0, thank you for contributing!

We have a hook for listening for keys: `useScopedHotkeys`. For reference, you can see how we use this hook to listen to the "Escape" key in `TableOptionsDropdownContent`.

Please note that the third argument for `useScopedHotkeys` is what we call a "HotkeyScope": it prevents conflicts between key listeners from different components.

For this third argument, you can just create a new enum entry in `front/src/modules/ui/table/types/TableHotkeyScope.ts`. For instance, you could name it `ColumnDropdown`. Then you can pass `TableHotkeyScope.ColumnDropdown` to the `useScopedHotkeys` hook!

2023-09-27 09:55 UTC, lucasbordeau commented
@Parvezkhan0 We prefer to use `useScopeHotkeys` as the generic way to handle hotkeys in Twenty, see our documentation : https://docs.twenty.com/developer/frontend/hotkeys 

You can follow along @thaisguigon 's comment which explains the details.

2023-09-27 10:11 UTC, Parvezkhan0 commented
@lucasbordeau Is it correct now ?

2023-09-27 14:39 UTC, charlesBochet commented
I have tested and this seems to be already working on main

I believe this already have been fixed in DropdownButton:
```
  useScopedHotkeys(
    'esc',
    () => {
      closeDropdownButton();
    },
    dropdownHotkeyScope.scope,
    [closeDropdownButton],
  );
```

2023-09-27 14:39 UTC, closed without merging