Feat: Add a multi-select on relation filters
twentyhq/twenty pull request #1822
Opened 2023-10-03 01:19 UTC by AyushAgrawal-A2

Closes #1719

- Create multi-select filters with operand select for the user, people & company entity.

https://github.com/twentyhq/twenty/assets/54364088/57f34179-3027-4b69-882b-6aaecf6ac800

2023-10-03 15:29 UTC, lucasbordeau requested changes

2023-10-04 01:00 UTC, AyushAgrawal-A2 commented on front/src/modules/ui/view-bar/components/FilterDropdownMultipleEntitySearchSelect.tsx
> +    Record<string, { name: string; isChecked: boolean }>
done

2023-10-04 14:09 UTC, lucasbordeau commented
I'm not able to see the changes you made, could you merge main and push ?

2023-10-04 15:57 UTC, charlesBochet commented
@Bonapara does design looks good to you? :)

2023-10-04 16:07 UTC, AyushAgrawal-A2 commented
> I'm not able to see the changes you made, could you merge main and push ?

Found a bug while screen recording. Just fixed it.

2023-10-05 14:05 UTC, lucasbordeau commented
@AyushAgrawal-A2 

- Can you see if `OverflowingTextWithTooltip` can fit your needs ? Using this component + a max-width on the chip ?
- The API is way cleaner, nice !
- Is it difficult for you to change the filter at every select/unselect, not after we exit the dropdown ? We can always do it in another ticket.
- We should erase the selected values when closing the dropdown. => Meaning we should reset the state of the multiple selection so we don't have the previous selection shown in the dropdown, but it seems to be fixed with your new changes !

2023-10-05 14:05 UTC, lucasbordeau commented on front/src/modules/ui/view-bar/components/FilterDropdownMultipleEntitySearchSelect.tsx
> +    setSelectedEntities((prev) =>
We avoid generic names even in lambdas, better to have `previousSelectedEntities`

2023-10-05 14:05 UTC, lucasbordeau commented on front/src/modules/ui/view-bar/components/FilterDropdownMultipleEntitySearchSelect.tsx
> +        if (entity.id === enitityId) {
`enitity`

2023-10-05 21:09 UTC, AyushAgrawal-A2 commented
> * Is it difficult for you to change the filter at every select/unselect, not after we exit the dropdown ? We can always do it in another ticket.

I actually first implemented per-click update. On every selection, the table was getting refreshed and the menu item order was also getting changed as the selected item would move to the top. I didn't like the user experience while testing it.
Can revert back if that is the desired behavior.

2023-10-06 08:13 UTC, Bonapara commented
> @Bonapara
> 
> 1. I have set the display name for multi-select filter as a comma-separated list. This will get too long.
>    ![image](https://user-images.githubusercontent.com/54364088/272644376-661591b0-3a65-4b43-8248-504220cc0673.png)
>    Options:
>    
>    * Trim it after a max length "Facebook, Google, Air..."
>    * Show full name if only one is selected and number if many e.g. "3 Selected"
>    * ??
> 2. Operand name in Operand Select menu
>    ![image](https://user-images.githubusercontent.com/54364088/272645467-d659ef2a-0058-4df0-b829-455d057edb1b.png)
> 3. Operand in Filter chip. "Company: NotIn ..." i.e. `: In` `: NotIn` part. I feel `: NotIn` is not readable.

Hi @AyushAgrawal-A2 

- For your first question, let's do you second suggestion → Show full name if only one is selected and number if many e.g. "3 Selected"
- For your second question I think we can keep the behavior of people operand name : "is" and "not" (without displaying "is" in the chip)

2023-10-06 09:52 UTC, lucasbordeau commented
> > * Is it difficult for you to change the filter at every select/unselect, not after we exit the dropdown ? We can always do it in another ticket.
> 
> I actually first implemented per-click update. On every selection, the table was getting refreshed and the menu item order was also getting changed as the selected item would move to the top. I didn't like the user experience while testing it. Can revert back if that is the desired behavior.

Good point, what are your thoughts on that @Bonapara, I feel like it's better to show changes on each click.

2023-10-06 11:02 UTC, AyushAgrawal-A2 commented
@lucasbordeau @Bonapara 
- Made all changes in "as per feedback" commit [fcb51a6](https://github.com/twentyhq/twenty/pull/1822/commits/fcb51a6e122cf57ba0473ce16b89ab96dde95fc3)
- Switched to per click update in last commit [364809e](https://github.com/twentyhq/twenty/pull/1822/commits/364809e114fa15e2629294e5be2daa522acb28cc)

Please try it and decide.

P.S.: storybook fix is pending, and can be fixed only after behavior is finalized

2023-10-08 19:04 UTC, Bonapara commented
> > > * Is it difficult for you to change the filter at every select/unselect, not after we exit the dropdown ? We can always do it in another ticket.
> > 
> > 
> > I actually first implemented per-click update. On every selection, the table was getting refreshed and the menu item order was also getting changed as the selected item would move to the top. I didn't like the user experience while testing it. Can revert back if that is the desired behavior.
> 
> Good point, what are your thoughts on that @Bonapara, I feel like it's better to show changes on each click.

I agree with your understanding. Implementing changes on each click could enhance the experience, but we should prevent the menu from reordering after each selection. The reordering should only occur when the dropdown is closed and then reopened. We should open a new issue for that.

2023-10-09 13:43 UTC, lucasbordeau commented
I'll let @charlesBochet review because I'm quite busy but seems ok for me !

2023-10-09 17:01 UTC, AyushAgrawal-A2 commented
@Bonapara 

> but we should prevent the menu from reordering after each selection. The reordering should only occur when the dropdown is closed and then reopened. We should open a new issue for that.

This will require refactoring and reviewing the same code again, Please let me fix this in this PR itself.

2023-10-09 19:57 UTC, AyushAgrawal-A2 commented
@lucasbordeau @charlesBochet @Bonapara 
Changes:-
- Fixed menu item reorder on item select/deselect.
- Fixed correct operand select on filter menu open.


https://github.com/twentyhq/twenty/assets/54364088/e53310ef-5240-4985-aa64-5d723b8cc483

Submitting again for review.

2023-11-03 15:52 UTC, lucasbordeau commented
Waiting for relation field type refactor with new flexible backend.

2023-12-07 13:30 UTC, closed without merging

2023-12-07 13:30 UTC, lucasbordeau commented
Hi @AyushAgrawal-A2, thank you very much for your efforts. 

After waiting for a long time, we have decided to implement this feature with the core team because it touches a lot of moving parts of the new architecture, in https://github.com/twentyhq/twenty/pull/2858.

Please feel free to tell us anything we might have missed in our implementation.