Prevent layout shift on page load
twentyhq/twenty pull request #2268
Opened 2023-10-28 08:09 UTC by brendanlaschke

Fixes the layout shift of the page as the navbar is loaded and animated to open. Also fixes the navbar collapse icon flashing.
Sadly this doesn't fix the other layout shift problem described in #1512.

https://github.com/twentyhq/twenty/assets/48770548/87e329ff-b8fc-471d-905a-8cadebe59e70

2023-10-30 14:16 UTC, lucasbordeau requested changes
Nice work, could you also fix the right shift when we open the left nav bar ?

2023-10-30 14:20 UTC, brendanlaschke commented
> Nice work, could you also fix the right shift when we open the left nav bar ?

I would love to fix it, if I had any clue what the problem was :) - the children of the StyledMainContainer just don't change their size...

2023-10-31 13:09 UTC, lucasbordeau commented
Ok let's address this in another PR then.

2023-10-31 13:09 UTC, lucasbordeau approved these changes

2023-10-31 13:09 UTC, merged