1991 empty state v1 for tables
twentyhq/twenty pull request #2273
Opened 2023-10-29 16:47 UTC by martins5225

This introduces an empty state feature to data tables for both standard and custom objects. 

The new EmptyTable component displays a user-friendly message and an optional action button when the table is empty,

2023-10-29 16:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/twentyhq/twenty?pullRequest=2273) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/twentyhq/twenty?pullRequest=2273) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/twentyhq/twenty?pullRequest=2273) it.</sub>

2023-10-30 12:39 UTC, lucasbordeau commented
Hi @martins5225, thanks for your proposal. This seems neat, could you clean up a little bit the files, and post some screenshot before/after so that @Bonapara can review the UX/UI ? Also is it linked to an existing issue ? If that's the case, could you link it ?

2023-10-30 12:40 UTC, lucasbordeau requested changes

2023-10-30 12:40 UTC, lucasbordeau commented on front/src/modules/ui/data/data-table/components/DataTable.tsx
> +  // const visibleTableColumns = useRecoilScopedValue(
Remove dead code

2023-10-30 12:40 UTC, lucasbordeau commented on front/src/modules/ui/data/data-table/components/DataTable.tsx
> +  const defaultOnClick = () => {
Prefer allowing undefined in EmptyTable onClick method. And check if onClick is defined in EmptyTable

2023-10-30 12:40 UTC, lucasbordeau commented on front/src/modules/ui/data/data-table/components/EmptyTable 2.tsx
> +import styled from '@emotion/styled';
Is this a duplicate ?

2023-10-30 22:09 UTC, martins5225 commented
> Hi @martins5225, thanks for your proposal. This seems neat, could you clean up a little bit the files, and post some screenshot before/after so that @Bonapara can review the UX/UI ? Also is it linked to an existing issue ? If that's the case, could you link it ?

HI @lucasbordeau Thank you for the feedback, I'll do the clean up and also include the screenshots. I don't think this is linked to an existing issue

2023-11-01 14:32 UTC, Bonapara commented
Hi @martins5225 Can you even provide a **screenshot video** of the feature? Can you make sure the content is well centered (No scroll should be possible) and that it doesn't **blink** before the content loading when there is 1+ record(s)?

2023-11-06 22:34 UTC, charlesBochet commented
@martins5225 I'm closing this PR due to inactivity. Feel free to re-open it with new changes and we will happily take another look :) Thanks for the help anyway!

2023-11-06 22:34 UTC, closed without merging