Update DropdownMenu.tsx
twentyhq/twenty pull request #2441
Opened 2023-11-12 13:43 UTC by joshLumpkin

closes #2392

changed width param. Allows calendar to have full width on dropdown menu

2023-11-12 13:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/twentyhq/twenty?pullRequest=2441) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/twentyhq/twenty?pullRequest=2441) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/twentyhq/twenty?pullRequest=2441) it.</sub>

2023-11-13 14:51 UTC, lucasbordeau requested changes
We need to keep the other dropdown menus as is.

For example the dropdown menu of filters needs to stay at the same size : 

<img width="214" alt="image" src="https://github.com/twentyhq/twenty/assets/26528466/14a33cc6-1a10-483d-827a-d98c700cd763">


With your fix it gets shrunk like this : 

<img width="180" alt="image" src="https://github.com/twentyhq/twenty/assets/26528466/e585f69c-64ed-4037-a40d-fcc08f5335a9">

2023-11-13 16:22 UTC, joshLumpkin commented
Got it, will update!

2023-11-14 11:18 UTC, bosiraphael commented
Thank you very much for your contribution, this issue has been fixed in #2486, so I'm closing the issue.

2023-11-14 11:18 UTC, closed without merging