2973-feat: Skeleton Loading Added
twentyhq/twenty pull request #2988
Opened 2023-12-14 13:36 UTC by Kanav-Arora

Closes #2973 

I found the issue but was unable to reproduce it, but I have made some changes if they work.

2023-12-15 10:03 UTC, lucasbordeau requested changes, later dismissed

2023-12-15 10:03 UTC, lucasbordeau commented on packages/twenty-front/src/modules/object-record/components/RecordShowPage.tsx
>    const { record } = useFindOneRecord({
Could you use the loading property from the Apollo query hook instead ?

2023-12-15 17:00 UTC, Kanav-Arora commented
Hi @lucasbordeau 
Done with the changes please check

2023-12-15 20:44 UTC, charlesBochet reviewed
@Kanav-Arora, I have left additional comments, then we can merge!

2023-12-15 20:44 UTC, charlesBochet commented on packages/twenty-front/src/modules/object-record/components/RecordShowPage.tsx
> +            {loading === false ? (
!loading

2023-12-15 20:44 UTC, charlesBochet commented on packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageLeftContainer.tsx
> +  children?: ReactElement[];
this feels wrong, I think we should force containers to have children

2023-12-15 20:44 UTC, charlesBochet commented on packages/twenty-front/src/modules/object-record/components/RecordShowPage.tsx
> +                <ShowPageLeftContainer />
`<ShowPageLeftContainer></ShowPageLeftContainer>`

2023-12-15 20:44 UTC, charlesBochet commented on packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageRightContainer.tsx
> +/* eslint-disable react-hooks/rules-of-hooks */
why do we need this? Feels wrong :)

2023-12-19 14:43 UTC, charlesBochet commented
@Kanav-Arora any update on this one? :)

2023-12-19 15:08 UTC, Kanav-Arora commented
Hi @charlesBochet on it
Sorry I was busy somewhere, pushing changes in an hour

2023-12-19 15:29 UTC, Kanav-Arora commented
Hi @charlesBochet 
Done

2023-12-20 08:55 UTC, charlesBochet approved these changes
@Kanav-Arora I have removed` if (!record) return <></>;` on line 132 which was making your fix not actually applied. And I have fixed the consequences of this.
Thanks for the help, as always!

2023-12-20 09:07 UTC, merged