Issue with floating buttons
twentyhq/twenty pull request #3160
Opened 2023-12-27 02:12 UTC by a-kud

Fixes #2800

before
![imagen](https://github.com/twentyhq/twenty/assets/14137213/781e9fed-4bff-43de-86eb-c1e6f2a7a080)

after
![imagen](https://github.com/twentyhq/twenty/assets/14137213/f9d9fd2c-008e-4d30-a2f3-6ea521ab8e95)

2023-12-27 10:09 UTC, lucasbordeau commented
@a-kud Thanks for your contribution, the original issue was a bit misleading, I updated it with more context so you can make the relevant changes.

2023-12-27 10:10 UTC, lucasbordeau commented on packages/twenty-front/src/modules/ui/input/button/components/FloatingButtonGroup.tsx
> +  background: ${({ theme }) => `linear-gradient(
We don't want a linear-gradient here.

2024-01-02 10:14 UTC, lucasbordeau requested changes
We're good with the position.

Here is the reference figma for Floating Buttons, please update the CSS to match the different states accordingly, the default state shouldn't have a blue border : https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=9580-52280&mode=dev

2024-01-05 10:26 UTC, charlesBochet commented
@a-kud Any update on this one? :)

2024-01-07 00:53 UTC, a-kud commented
I have a high workload right now, feel free to use my PR as a starter to fix the issue.

2024-01-07 00:53 UTC, closed without merging

2024-01-11 11:00 UTC, charlesBochet commented
Ok, no worries! We can pick this back a little later :)