Gary121github patch #3166
twentyhq/twenty pull request #3226
Opened 2024-01-03 20:14 UTC by GARY121github

## refactor: improve generateEmptyFieldValue function

- Optimize handling of MultiSelect and Select cases
- Provide a default value for Select based on FieldSelectValue
- Enhance code readability and maintainability

2024-01-03 20:18 UTC, GARY121github commented
hello @lucasbordeau ,
I am new to open source and I am still understanding the code base.
Can you please help me to understand the issue more clearly?

2024-01-03 20:25 UTC, charlesBochet requested changes
Thanks for the contribution, I have left comments!

2024-01-03 20:25 UTC, charlesBochet commented on packages/twenty-front/src/modules/object-record/utils/generateEmptyFieldValue.ts
> +        fieldMetadataItem.type === FieldMetadataType.MultiSelect ||
I am not sure to understand why you choose to handle this in the default section. This should stay in their own case

2024-01-03 20:25 UTC, charlesBochet commented on packages/twenty-front/src/modules/object-record/utils/generateEmptyFieldValue.ts
> +        fieldMetadataItem.type === FieldMetadataType.MultiSelect ||
Also multi select is not implemented yet on the backend so it should stay has non implemented

2024-01-03 20:25 UTC, charlesBochet commented on packages/twenty-front/src/modules/object-record/utils/generateEmptyFieldValue.ts
> +          color: 'DEFAULT_COLOR', // Replace with the actual default color
let's take the first possible option color and first select option if the field is non nullable and leave it null if nullable

2024-01-03 20:25 UTC, charlesBochet commented
Also, could you please add a first jest test on this function?
And update the PR title :)

2024-01-05 09:43 UTC, charlesBochet reviewed
@GARY121github You have marked the comments as resolved but I don't see the related change? :)

2024-01-05 16:33 UTC, GARY121github commented
I cannot understand the issue properly can you please guide me?
```
case FieldMetadataType.MultiSelect: {
    // Handle MultiSelect-specific logic
    if (!backendSupportsMultiSelect) {
      throw new Error('MultiSelect not implemented on the backend yet');
    }
    // Additional MultiSelect handling
    break;
  }
  case FieldMetadataType.Select: {
    // Handle Select-specific logic
    const defaultSelectValue = {
      color: 'DEFAULT_COLOR', // Replace with the actual default color
      label: '',
      __typename: 'FieldSelectValue',
    };
    return defaultSelectValue;
  }
  default: {
    throw new Error('Unhandled FieldMetadataType');
  }
```
Is this code completing your requirements?
I have separated them from the default case.

2024-01-05 17:03 UTC, charlesBochet commented
@GARY121github It looks good but it's not what I see in your PR

2024-01-05 17:04 UTC, charlesBochet commented
![Uploading image.png…]()

2024-01-05 17:31 UTC, GARY121github commented
> @GARY121github It looks good but it's not what I see in your PR

I have updated the code according to your explanation should I create

2024-01-05 17:33 UTC, charlesBochet commented
Here is what I see:
<img width="1320" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/cf639cec-8f02-4ba2-90cd-9ecbbe667b54">

2024-01-08 16:58 UTC, GARY121github commented
@charlesBochet I have sent new PR can you please review and merge it

2024-01-11 10:53 UTC, charlesBochet approved these changes
Thank you @GARY121github 
Your code was referencing an undefined backendSupportsMultiSelect variable. I have removed it as the backend does not support it at all yet
Also, we have changed the typing of Select (it use to be an object label + color), it is now a scalar which simplifies it

2024-01-11 11:00 UTC, merged