Add rate limiting in the server using built in Nest.js capability
twentyhq/twenty pull request #3566
Opened 2024-01-20 18:02 UTC by jss475

[#3545 ](https://github.com/twentyhq/twenty/issues/3545)

- Add rate limiting for graphql and http requests in the backend using built in Nest.js capability

2024-01-23 14:12 UTC, magrinj requested changes
Thanks for your contribution !
Some changes and tests are needed before merging it 🙂

2024-01-23 14:12 UTC, magrinj commented on packages/twenty-server/.env.test
> +NON_LOGGED_IN_LIMIT=10
@jss475 Better to remove unused env variables that you add

2024-01-23 14:12 UTC, magrinj commented on packages/twenty-server/src/app.module.ts
> +      provide: APP_GUARD,
I'm not sure if it's going to work for the flexible schema, @charlesBochet I think we need to test this

2024-01-23 17:38 UTC, jss475 commented on packages/twenty-server/src/guards/gql-throttler.guard.ts
> +import { ThrottlerGuard } from '@nestjs/throttler/dist';
@magrinj I thought the same thing, but for me going into the /dist folder is the only way the imports work. Maybe it's just how my files are configured(?)

2024-01-23 17:39 UTC, jss475 commented on packages/twenty-server/src/guards/gql-throttler.guard.ts
> +  getRequestResponse(context: ExecutionContext) {
Good call! Thank you!

2024-02-06 08:24 UTC, magrinj commented on packages/twenty-server/src/integrations/environment/environment.service.ts
> +  }
```suggestion
```

2024-02-06 08:25 UTC, magrinj commented on packages/twenty-server/src/integrations/environment/environment.service.ts
> +  }
```suggestion
```

2024-02-06 08:27 UTC, magrinj requested changes

2024-02-06 08:27 UTC, magrinj commented on packages/twenty-server/.env.example
> +
```suggestion
# LOGGED_IN_LONG_TTL=3000
# LOGGED_IN_LONG_LIMIT=20
```

2024-02-06 08:27 UTC, magrinj commented on packages/twenty-server/.env.test
> +
```suggestion
# LOGGED_IN_LONG_TTL=3000
# LOGGED_IN_LONG_LIMIT=20
```

2024-02-06 12:06 UTC, magrinj commented
@jss475 Thanks for your work, I've change the code because our graphQL schema is dynamically constructed, so `@nestjs/throttler` was not handling request on the dynamic side.
Instead I've created a `graphql-yoga` plugin.
cc @charlesBochet

2024-02-07 16:49 UTC, charlesBochet approved these changes
Approved with comments. We should also add the environment variables to the documentation

2024-02-07 16:49 UTC, charlesBochet commented on packages/twenty-server/.env.example
> +# LOGGED_IN_LONG_TTL=
I am not sure about this naming, reading the code to understand what it is

2024-02-07 16:49 UTC, charlesBochet commented on packages/twenty-server/.env.example
> +# LOGGED_IN_LONG_TTL=
API_RATE_LIMITING_TTL
API_RATE_LIMITING_LIMIT

2024-02-07 17:06 UTC, charlesBochet approved these changes

2024-02-07 17:11 UTC, merged