feat: added webhook list section and updated api key section
twentyhq/twenty pull request #3567
Opened 2024-01-21 12:49 UTC by lakshay-saini-au8

Added the Webhook List section and updated the UI for api key section

https://github.com/twentyhq/twenty/issues/3271

<img width="1119" alt="Screenshot 2024-01-21 at 6 14 44 PM" src="https://github.com/twentyhq/twenty/assets/19304527/1843f645-764b-4646-80c6-529091a04db7">

2024-01-22 10:18 UTC, martmull requested changes
Hey @lakshay-saini-au8 thank you very much for this PR. It is really good work. Left some comments

2024-01-22 10:18 UTC, martmull commented on packages/twenty-front/src/pages/settings/developers/SettingsDevelopersApiKeys.tsx
> +  return (
there is an issue when no apiKeys or webhook are listed 
![image](https://github.com/twentyhq/twenty/assets/29927851/2be19e75-e482-40ca-824b-e3db45b8e5ef)
![image](https://github.com/twentyhq/twenty/assets/29927851/874a7cd9-cecb-4c61-a0a3-1dd61cacbeb1)
Think you should remove the last line in the Table when there is no apiKey. Same for webhook. Would look like 
![image](https://github.com/twentyhq/twenty/assets/29927851/302a66bd-78bf-4ce2-8859-14a9a4937acc)

Seen with @Bonapara

2024-01-22 10:18 UTC, martmull commented on packages/twenty-front/src/App.tsx
>                          path={SettingsPath.Developers}
think we should update the `settingsPath.Developers` value
![image](https://github.com/twentyhq/twenty/assets/29927851/e53efeae-9777-43b4-8d04-b1d7831acf87)
Think you can just replace it by `""`. Update hrefs in `SettingsDevelopersApiKeyDetail` and `SettingsDevelopersApiKeysNew`

2024-01-22 10:18 UTC, martmull commented on packages/twenty-front/src/modules/settings/developers/components/SettingsDevelopersWebhookTableRow.tsx
> +  word-break: break-all;
style does not match perfectly with figma 
![image](https://github.com/twentyhq/twenty/assets/29927851/85fccd53-adb0-498a-9460-ca346b81f6c4)
![image](https://github.com/twentyhq/twenty/assets/29927851/a2657dac-26f7-487a-8b33-f4f2290b9ae0)
Can you update color?
```suggestion
  color: ${({ theme }) => theme.font.color.primary};
  word-break: break-all;
```

2024-01-25 11:20 UTC, martmull commented
Hey @lakshay-saini-au8, I will pass the changes on that feature to merge it quickly. Thank you for your work, it was great job! Have a nice day

2024-01-25 14:26 UTC, lucasbordeau requested changes

2024-01-25 14:26 UTC, lucasbordeau commented on packages/twenty-front/src/pages/settings/developers/SettingsDevelopersWebhooks.tsx
> +  const [webhooks, setWebhooks] = useState<Array<WebhookFieldItem>>([]);
We can derivate webhooks directly from the return of useFindManyRecords.

Plus onCompleted is not always re-triggered if data changes.

2024-01-25 16:38 UTC, lucasbordeau approved these changes

2024-01-25 16:38 UTC, martmull approved these changes

2024-01-25 16:39 UTC, merged