feat: display record identifier field as first column in table
twentyhq/twenty pull request #3788
Opened 2024-02-02 17:35 UTC by thaisguigon

& forbid hiding and moving record identifier column

Closes #3303

2024-02-06 15:02 UTC, lucasbordeau commented
Should we move auto-complete "Untitled" on the record identifier field ?

<img width="767" alt="image" src="https://github.com/twentyhq/twenty/assets/26528466/0476a57e-b065-4a73-a06e-7e355fb19972">

2024-02-06 15:04 UTC, lucasbordeau commented
Is it relevant to fix this in this PR ?

The breadcrumb should show the record identifier content : 

<img width="400" alt="Capture d’écran 2024-02-06 à 16 03 03" src="https://github.com/twentyhq/twenty/assets/26528466/290159d9-6c47-4ab8-8324-ed294956e44a">

2024-02-06 15:07 UTC, lucasbordeau commented on packages/twenty-front/src/modules/object-record/record-table/states/selectors/tableLabelIdentifierColumnSelectorScopeMap.ts
> +        ).map(({ fieldMetadataId }) => fieldMetadataId);
Couldn't we use a dedicated selector for that ?

2024-02-06 17:23 UTC, thaisguigon commented
> Should we move the "+" new button on the record identifier row ?

Good catch, done!

2024-02-06 17:37 UTC, thaisguigon commented
> Is it relevant to fix this in this PR ?
> 
> The breadcrumb should show the record identifier content

Absolutely! Done, thank you!

2024-02-06 17:44 UTC, thaisguigon commented
> Should we move auto-complete "Untitled" on the record identifier field ?

Not sure how to go about this one, as the "Untitled" value is generated on backend (default value for the "name" field). Maybe @Weiko has some input on this?

2024-02-07 08:43 UTC, charlesBochet commented
@Weiko @thaisguigon
From a DB perspective, it is non nullable because all text fields are non nullable have a default value: "". 

From an API perspective, all fields are non required because they are either nullable in DB or have a default value. (here name has default value so is non-required)

2024-02-07 09:02 UTC, charlesBochet requested changes
@thaisguigon I think we are adding too much complexity on the recordTable:
- I think we should aim to reduce the number of selectors we have as this gets quickly out of control : contributors are not forced to re-use selectors so they usually re-code the logic again and again, or introduce their own selectors that are slightly different. It's hard to get this factored. I prefer having basic states and basic selector and factorize logic in components or utils if it's needed, but usually it is not: for example the availableTableColumnKey is only extracting the availableTableColumnKey
- I think we should not add all this logic about labelIdentifiers fetching in the table itself. We could add it to mapViewFieldsToColumnDefinitions "isLabelIdentifer"?

2024-02-08 09:43 UTC, thaisguigon commented
> @thaisguigon I think we are adding too much complexity on the recordTable:
> 
> * I think we should aim to reduce the number of selectors we have as this gets quickly out of control : contributors are not forced to re-use selectors so they usually re-code the logic again and again, or introduce their own selectors that are slightly different. It's hard to get this factored. I prefer having basic states and basic selector and factorize logic in components or utils if it's needed, but usually it is not: for example the availableTableColumnKey is only extracting the availableTableColumnKey
> * I think we should not add all this logic about labelIdentifiers fetching in the table itself. We could add it to mapViewFieldsToColumnDefinitions "isLabelIdentifer"?

@charlesBochet Done:
- removed some selectors
- added some utils
- moved the label identifier logic to `mapViewFieldsToColumnDefinitions`

2024-02-09 11:36 UTC, charlesBochet approved these changes

2024-02-09 11:36 UTC, merged