feat: adding metadata open-api endpoints and updating docs
twentyhq/twenty pull request #4170
Opened 2024-02-25 00:11 UTC by AdityaPimpalkar

closes - #4089

Feedback is appreciated! Thanks! :)

2024-02-25 08:26 UTC, charlesBochet commented
Thanks @AdityaPimpalkar! @martmull will take a look on Monday :)

2024-02-27 09:32 UTC, martmull requested changes
Hey @AdityaPimpalkar, thank you for your PR. Great work! I've added some comments. Also, the general OpenAPI Schema endpoints are broken because the paths are incorrect. Would you mind fixing them? Thank you!

2024-02-27 14:47 UTC, AdityaPimpalkar commented on packages/twenty-docs/src/pages/rest-api/metadata.tsx
> +import React, { useEffect, useState } from 'react';
Done!

2024-03-05 10:35 UTC, martmull approved these changes

2024-03-05 10:37 UTC, merged