Fixed index column stickiness mobile
twentyhq/twenty pull request #4206
Opened 2024-02-27 11:38 UTC by jeet1desai

Fixes #4155 

https://github.com/twentyhq/twenty/assets/52026385/928e9f38-d49a-46be-89ea-045f8ae6c149

2024-02-29 15:45 UTC, thaisguigon requested changes
Hi @jeet1desai, thank you for your contribution!

I pushed an additional commit to remove `RecordTableFirstColumnScrollEffect` and simplify the "frozen columns" logic in `RecordTable`.

I also left some other comments. Nice work overall!

2024-02-29 15:45 UTC, thaisguigon commented on packages/twenty-front/src/modules/object-record/record-table/components/RecordTableHeaderCell.tsx
> +  margin-left: ${({ theme }) => theme.spacing(1.5)};
Also, we should disable resizing the label identifier column when it's in mobile "sticky" mode.

We could disable it like this same file (`RecordTableHeaderCell`):

```typescript
  const isMobile = useIsMobile();
  const scrollLeft = useRecoilValue(scrollLeftState);

  const disableColumnResize =
    column.isLabelIdentifier && isMobile && scrollLeft > 0;

  // ...

  {!disableColumnResize && (
    <StyledResizeHandler
      className="cursor-col-resize"
      role="separator"
      onPointerDown={() => {
        setResizedFieldKey(column.fieldMetadataId);
      }}
    />
  )}
```

2024-03-01 09:29 UTC, thaisguigon requested changes, later dismissed
Hi @jeet1desai, thank you for addressing the comments!
I see you resolved most of them, the only one missing is https://github.com/twentyhq/twenty/pull/4206#discussion_r1507703211, could you look into it?
This is currently breaking the typings!

2024-03-04 15:41 UTC, charlesBochet approved these changes
Thank you @jeet1desai 
and thanks @thaisguigon for the review!

2024-03-04 15:41 UTC, merged