Added CurrencyFieldInput design
twentyhq/twenty pull request #4254
Opened 2024-03-01 09:10 UTC by jeet1desai

Closes #4123

2024-03-04 10:19 UTC, magrinj commented
Hello @jeet1desai, thanks for your contribution, is it still a work in progress as the PR is marked as a draft ?

2024-03-04 10:39 UTC, jeet1desai commented
Hello @magrinj, It's still not completed. I need support if you can help me.

Whenever I try to edit and select a different currency code, it defaults to USD. I have also attached the video.

[defaults to USD.webm](https://github.com/twentyhq/twenty/assets/52026385/0899ecdb-c8ce-476c-92dc-e91649766ca2)

2024-03-04 15:16 UTC, lucasbordeau reviewed
Please see in `computeDraftValueFromFieldValue.ts` 

```ts 
return {
  amount: fieldValue?.amountMicros ? fieldValue.amountMicros / 1000000 : '',
  currenyCode: CurrencyCode.USD,
} as unknown as FieldInputDraftValue<FieldValue>;
```

2024-03-04 15:16 UTC, lucasbordeau commented on packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/CurrencyFieldInput.tsx
> +  const handleSelect = (newValue: string) => {
All newValue args should be of type `Currency` now.

```ts
const handleEnter = (newCurrencyValue: Currency) => {
```

2024-03-06 07:55 UTC, jeet1desai commented
> Please see in `computeDraftValueFromFieldValue.ts`
> 
> ```ts
> return {
>   amount: fieldValue?.amountMicros ? fieldValue.amountMicros / 1000000 : '',
>   currenyCode: CurrencyCode.USD, // <== Maybe change this hard coded value to something dynamic here ? Example : fieldValue.currencyCode ?
> } as unknown as FieldInputDraftValue<FieldValue>;
> ```

Thank you @lucasbordeau, It worked

2024-03-07 13:54 UTC, lucasbordeau requested changes
@jeet1desai Nice work.

Some minor differences : 

Figma : 

<img width="270" alt="image" src="https://github.com/twentyhq/twenty/assets/26528466/57dddb49-acf5-4677-8e80-28e0bf91e35a">

React app : 

<img width="284" alt="image" src="https://github.com/twentyhq/twenty/assets/26528466/f6300c93-1a0f-41fe-afd4-99c2cf837389">

- Currency icon is too thick
- Currency text is too light, the font-weight is 500 in Figma
- The border between the currency text and the input should be a clean vertical bar

2024-03-08 20:30 UTC, lucasbordeau approved these changes

2024-03-08 20:30 UTC, merged