[messaging] add more logs in exceptions
twentyhq/twenty pull request #4256
Opened 2024-03-01 10:13 UTC by Weiko

2024-03-01 11:02 UTC, charlesBochet approved these changes

2024-03-04 10:25 UTC, magrinj requested changes

2024-03-04 10:25 UTC, magrinj commented on packages/twenty-server/src/workspace/workspace-datasource/workspace-datasource.service.ts
> +      throw new Error(
@Weiko Hmm not sure if it's the right level to catch the error, we should let query throw and let the exception handlers transform the errors properly, as we're also mapping some of the `pg_graphql` and `postgres` errors

2024-03-04 10:39 UTC, magrinj approved these changes

2024-03-04 13:05 UTC, merged