feat: change condition of duplicate check
twentyhq/twenty pull request #4273
Opened 2024-03-02 16:42 UTC by rostaklein

fixes https://github.com/twentyhq/twenty/issues/4268

2024-03-03 10:11 UTC, FelixMalfait commented on packages/twenty-server/src/workspace/workspace-query-builder/factories/find-duplicates-query.factory.ts
> +          { eq: `%${argsData[columnName]}%` },
Do '%' work with equal statements? I didn't test locally yet but I would have guessed this doesn't work and we should just have eq: `${argsData[columnName]}` ?

2024-03-03 10:11 UTC, FelixMalfait commented
Thank you!

2024-03-04 09:54 UTC, magrinj requested changes
Thanks for your PR, few minor comments :)

2024-03-05 11:11 UTC, magrinj approved these changes
LGTM ! Thanks for the changes and your contribution :)

2024-03-05 11:11 UTC, merged