fix: removed onhover show from View Switcher Lock Design
twentyhq/twenty pull request #4671
Opened 2024-03-26 16:22 UTC by HrushiYadav

Fix #4653

2024-03-26 17:04 UTC, Kanav-Arora commented
Hi @HrushiYadav 
Thanks for contributing!

There should be a minor change. In the below screenshot you can see the pencil icon is also static. 
Only the locked view should be static but the pencil icon should be visible only on hover.
Moreover please set the icon color to font.color.tertiary

<img width="457" alt="Screenshot 2024-03-26 at 10 32 40 PM" src="https://github.com/twentyhq/twenty/assets/62852363/37a228d1-ce76-44fb-b1fc-60efdb15eda4">

2024-03-26 17:05 UTC, Kanav-Arora commented on packages/twenty-front/src/modules/ui/navigation/menu-item/internals/components/StyledMenuItemBase.tsx
> +    position: static;
Here and the old code was better which had a hover block

2024-03-26 17:06 UTC, Kanav-Arora requested changes

2024-03-26 17:06 UTC, Kanav-Arora commented on packages/twenty-front/src/modules/ui/navigation/menu-item/internals/components/StyledMenuItemBase.tsx
> +    position: static;
Here and the old code was better which had a hover block

2024-04-02 04:44 UTC, HrushiYadav commented
@Kanav-Arora It will take time as I'm facing some issues with the setup

2024-04-04 10:54 UTC, FelixMalfait commented
Closing for now but feel free to re-open if problem isn't fixed by then! Thanks for your attempt to contribute 💙

2024-04-04 10:54 UTC, closed without merging

2024-04-04 10:58 UTC, Kanav-Arora commented
@HrushiYadav 
When you'll complete the setup feel free to reopen and continue working on this issue.