Fix "Delete" action on the Kaban view
twentyhq/twenty pull request #5646
Opened 2024-05-29 09:47 UTC by pacyL2K19

# This PR

- Fixes #5520 
- Created a shared confirmation modal component for the `ContextMenu` and the `ActionBar` components to avoid code repetition - with its storybook file

Looking forward to getting feedback

2024-06-04 09:29 UTC, martmull requested changes
Hey, the right click delete in properly fixed.

But I see a functional issue:
- if i right click on an opportunity the modal appears
- then I click outside to make the modal disapear
- then I select two other opportunities
- then I see the "right click modal" appears near the first opportunity, not at the bottom page like it should

@pacyL2K19 Do you think you can provide a fix for that also?

Thanks

2024-06-04 09:42 UTC, pacyL2K19 commented
> Hey, the right click delete in properly fixed.
> 
> But I see a functional issue:
> 
> * if i right click on an opportunity the modal appears
> * then I click outside to make the modal disapear
> * then I select two other opportunities
> * then I see the "right click modal" appears near the first opportunity, not at the bottom page like it should
> 
> @pacyL2K19 Do you think you can provide a fix for that also?
> 
> Thanks

Sure @martmull 
Working on it asap

2024-06-05 09:24 UTC, pacyL2K19 commented
> > Hey, the right click delete in properly fixed.
> > But I see a functional issue:
> > 
> > * if i right click on an opportunity the modal appears
> > * then I click outside to make the modal disapear
> > * then I select two other opportunities
> > * then I see the "right click modal" appears near the first opportunity, not at the bottom page like it should
> > 
> > @pacyL2K19 Do you think you can provide a fix for that also?
> > Thanks
> 
> Sure @martmull Working on it asap

Hi @martmull, the fix to the above comment has been pushed, please have a look and let me know how you find it

2024-06-05 10:45 UTC, martmull commented
@pacyL2K19 thanks, that is better, but still not exactly the expected behavior.
We want 
- the bottom ActionBar to be displayed each time we select an opportunity
- the opportunity actionBar to be displayed when we right click on the opportunity 

https://github.com/twentyhq/twenty/assets/29927851/431e8185-4a2c-4f8b-b2c5-e8533a09dde6

2024-06-06 09:20 UTC, pacyL2K19 commented
> @pacyL2K19 thanks, that is better, but still not exactly the expected behavior. We want
> 
> * the bottom ActionBar to be displayed each time we select an opportunity
> * the opportunity actionBar to be displayed when we right click on the opportunity
> 
>  Enregistrement.de.l.ecran.2024-06-05.a.12.43.00.mov

Hi @martmull 
Just pushed my latest change, we should be good now, please have a look

2024-06-06 09:22 UTC, pacyL2K19 reviewed
Here's what I have
https://www.loom.com/share/1fb6737603b4492687b0814148361829?sid=3eb6366f-4e5f-42c8-9b88-9605ac7015a1

2024-06-07 15:23 UTC, martmull approved these changes
Hey, there is still some edge cases, but it LGTM and the delete modal bahavior is far better than before. Thank you very much!

2024-06-07 15:23 UTC, merged