Add description for Developers/webhook page
twentyhq/twenty pull request #6327
Opened 2024-07-18 20:32 UTC by abdulqdaer-q

2024-07-22 12:36 UTC, thomtrp requested changes
@abdulqdaer-q thank you for contributing!
I added a few comments

2024-07-22 12:36 UTC, thomtrp commented on packages/twenty-front/src/pages/settings/developers/webhooks/SettingsDevelopersWebhooksNew.tsx
> +        </Section>
please remove this section. It should only appear on edit mode

2024-07-22 12:36 UTC, thomtrp commented on packages/twenty-server/src/modules/webhook/standard-objects/webhook.workspace-entity.ts
> +  description: string;
description should be nullable since it will be empty for all existing webhook

2024-07-22 12:36 UTC, thomtrp commented on packages/twenty-front/src/pages/settings/developers/webhooks/SettingsDevelopersWebhookDetail.tsx
> +                disabled
should be enabled

2024-07-22 12:36 UTC, thomtrp commented on packages/twenty-front/src/pages/settings/developers/webhooks/SettingsDevelopersWebhookDetail.tsx
> +                disabled
When edited, save button and cancel button should be displayed so we can save the change. You can see how this is done for `SettingsObjectEdit` component

2024-07-22 12:36 UTC, thomtrp commented on packages/twenty-front/src/pages/settings/developers/webhooks/SettingsDevelopersWebhooksNew.tsx
> +    description: '',
should be null by default

2024-07-27 02:32 UTC, abdulqdaer-q commented
@thomtrp Comments have been resolved

2024-07-31 08:46 UTC, thomtrp approved these changes
LGTM @abdulqdaer-q ✅

2024-07-31 08:59 UTC, merged