Make api name editable and add expiry
twentyhq/twenty pull request #6473
Opened 2024-07-31 10:33 UTC by prateekj117

Fixes #6302

2024-08-01 09:23 UTC, martmull requested changes
Think we should use a recoilState to store the apiKey and get it in ApiKeyNameInput. Current code does not work properly as it removes the apiKeyToken display when a new api key is created

2024-08-01 11:02 UTC, prateekj117 commented on packages/twenty-front/src/pages/settings/developers/api-keys/SettingsDevelopersApiKeyDetail.tsx
> +  }, [apiKeyData, setApiKeyName]);
@martmull CMIIR, but I would need to make a new atom/state for APIKey, or maybe a Familystate, as I cannot find any already for APIKey in `settings/developers/states`.

And then use those to edit the name in the main state directly inside the ApiKeyNameInput component.

2024-08-01 11:25 UTC, prateekj117 commented on packages/twenty-front/src/pages/settings/developers/api-keys/SettingsDevelopersApiKeyDetail.tsx
> +  }, [apiKeyData, setApiKeyName]);
@martmull I think I can replace the use of `useEffect` event by using the onCompleted in `useFindOneRecord`.

Also, I can check the loading state and disable the input until the data is fetched.

2024-08-02 07:33 UTC, prateekj117 commented
@martmull This is ready for another round.

2024-08-02 09:06 UTC, martmull requested changes
added one commit to remove wrong error logging.
It does not work properly, when creating a new api Key, the token is whipped after apiKeyName is set so user cannot copy it. We need to work a little bit more on that

2024-08-02 11:29 UTC, martmull approved these changes
The fix required quite major changes so I did it @prateekj117. Think we are good to merge now, thank you for your contribution!

2024-08-02 11:31 UTC, merged