Fix cursor should not be pointer when record image identifier is not Editable
twentyhq/twenty pull request #7320
Opened 2024-09-29 15:03 UTC by sachinks07

- This PR solves the issue Cursor should not be "pointer" when record image identifier is not editable #7277

2024-09-30 09:22 UTC, martmull requested changes
Thanks, added a suggestion to simplify changes

2024-09-30 09:22 UTC, martmull commented on packages/twenty-front/src/modules/object-record/record-show/components/RecordShowContainer.tsx
> +      isAvatarEditable={objectNameSingular === 'person'}
```suggestion
```

2024-09-30 09:22 UTC, martmull commented on packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageSummaryCard.tsx
> +  isAvatarEditable?: boolean;
```suggestion
```

2024-09-30 09:22 UTC, martmull commented on packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageSummaryCard.tsx
> +  isAvatarEditable = false,
```suggestion
```

2024-09-30 09:22 UTC, martmull commented on packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageSummaryCard.tsx
> +      <StyledAvatarWrapper isAvatarEditable={isAvatarEditable}>
```suggestion
      <StyledAvatarWrapper isAvatarEditable={!!onUploadPicture}>
```

2024-09-30 10:18 UTC, sachinks07 commented
@martmull Thanks for the suggestion. Have made the changes with respect to the suggestions.

2024-10-01 07:02 UTC, martmull approved these changes
LGTM thank you!

2024-10-01 07:02 UTC, merged