Feat : Toggle Eye Icon to Expand/Collapse Kanban Card
twentyhq/twenty pull request #7396
Opened 2024-10-02 12:58 UTC by Vardhaman619

This pull request implements the functionality to toggle the eye icon in Kanban cards to expand or collapse the card details.

#7389 

[toogle-button-in-kanban-card.webm](https://github.com/user-attachments/assets/3bc1a31c-4053-429a-95e7-aa98188c39e4)

2024-10-02 19:43 UTC, ehconitin commented on packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCard.tsx
> +
lets not remove onMouseLeaveBoard

2024-10-02 19:44 UTC, ehconitin commented on packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCard.tsx
> +
```suggestion
    const onMouseLeaveBoard = () => {
    if (isCompactModeActive) {
      setIsCardInCompactMode(true);
    }
  };
```

2024-10-02 19:45 UTC, ehconitin commented on packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCard.tsx
>          selected={isCurrentCardSelected}
```suggestion
        selected={isCurrentCardSelected}
        onMouseLeave={onMouseLeaveBoard}
```

2024-10-02 19:48 UTC, ehconitin commented on packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCard.tsx
>                    />
```suggestion
                     <LightIconButton
                    Icon={isCardInCompactMode ? IconEye : IconEyeOff}
                    accent="tertiary"
                    onClick={(e) => {
                      e.stopPropagation();
                      setIsCardInCompactMode((prev) => !prev);
                    }}
                  />
```

2024-10-02 19:50 UTC, ehconitin commented on packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCard.tsx
>                      accent="tertiary"
icon should be conditionally rendered
eg - 
   Icon={isCardInCompactMode ? IconEye : IconEyeOff}

2024-10-02 19:50 UTC, ehconitin requested changes
Left some comments! ;)

2024-10-04 15:47 UTC, Vardhaman619 commented
@ehconitin

2024-10-04 17:38 UTC, ehconitin commented
@Bonapara 
Kept onMouseLeaveBoard with a debounced call of 800ms
Behaviour - 

https://github.com/user-attachments/assets/8945d2b0-9da0-4c11-9edb-f5c04ab23128

2024-10-04 18:34 UTC, ehconitin commented
@FelixMalfait 
renamed isCardInCompactMode to isCardExpanded because its more of a toggle now.
made onMouseLeaveBoard to have a debounced call - can remove if card is to immediately close on mouse leave.
Thanks :)

2024-10-05 08:20 UTC, FelixMalfait commented
Great points @ehconitin agree with both! Thank you

Thanks @Vardhaman619!

2024-10-05 08:20 UTC, FelixMalfait approved these changes

2024-10-05 09:03 UTC, ehconitin approved these changes

2024-10-05 09:04 UTC, merged