Add current workspace member option to workspaceMember relation field filter (#8016)
twentyhq/twenty pull request #8950
Opened 2024-12-09 01:40 UTC by eliasylonen

Not yet ready to be merged, but close!

Issue: #8016

2024-12-09 08:03 UTC, FelixMalfait commented
Great work as always! Starting to play around with it, noticed a first bug: 

https://github.com/user-attachments/assets/7f3d2d39-d9f6-4f6d-90b7-70cebc3af8e6

2024-12-09 08:04 UTC, FelixMalfait commented
In a followup PR / issue, could you maybe add an "assigned to me" view in "tasks-all.view.ts" file (this will only apply to new workspaces). This will make your feature more discoverable

2024-12-09 09:23 UTC, FelixMalfait commented
I think we can forget the "No assignee" from the initial issue as there is already "is empty which is good enough"

2024-12-09 09:24 UTC, FelixMalfait commented
Maybe create a followup issue to add it on the other side of the relationship?

<img width="290" alt="Screenshot 2024-12-09 at 10 23 17" src="https://github.com/user-attachments/assets/50bf5ac3-2a39-4434-9101-c92b497ace35">

2024-12-09 14:41 UTC, lucasbordeau commented
Please fix the tests

2024-12-09 14:47 UTC, lucasbordeau commented
Could you also verify that your IDE is correctly configured ? The lint problem on the tests and the prettier/eslint problems should not be part of your commit since it should be auto-fixed at save.

2024-12-09 15:42 UTC, lucasbordeau requested changes
With selectedRecordIdsAndSpecialIds, the naming tells us that there's a code smell, "DoingThisAndThat" indicates that we should split this into two distinc flows that join at the right abstraction level.

Here we should keep the previous flow as it is, with utils instead of hooks.

The changes seems to be only for relations and selection. You should explore a solution where you create recoil atoms for storing the state of what your new UI components are doing, then using those atoms where it's really needed, and copy/paste at multiple place if that's the things to do.

For example here contextStoreFilters seems to be more appropriate to store your additional current workspace member filter, and maybe a specific parallel hook/util could handle turning the click into a record filter and modify this state ?

2024-12-09 15:42 UTC, lucasbordeau commented on packages/twenty-front/src/modules/views/view-filter-value/utils/resolveBooleanViewFilterValue.ts
> +export const resolveBooleanViewFilterValue = (viewFilterValue: string) =>
We can keep the previous function, we don't strive to compact the code in this codebase, it's okay to keep things explicit and less compact.

2024-12-09 15:42 UTC, lucasbordeau commented on packages/twenty-front/src/modules/views/view-filter-value/utils/resolveDateViewFilterValue.ts
>  export const resolveDateViewFilterValue = <O extends ViewFilterOperand>(
Is this refactor needed for this feature ?

2024-12-09 15:42 UTC, lucasbordeau commented on packages/twenty-front/src/modules/views/hooks/useResolveFilterValue.ts
> +  const resolveFilterValue = <
We should keep this as a util

2024-12-09 15:42 UTC, lucasbordeau commented on packages/twenty-front/src/modules/views/view-filter-value/utils/resolveNumberViewFilterValue.ts
>  export const resolveNumberViewFilterValue = (
Is this refactor needed ?

2024-12-09 15:42 UTC, lucasbordeau commented on packages/twenty-front/src/utils/validation-schemas/safeStringArrayJSONSchema.ts
> +export const safeStringArrayJSONSchema = z
Ok to extract this as it was but the validation seems to introduce a silent error that returns [], could we throw or  return a wrong validation state instead when the value is really not parsable as an array ?

2024-12-21 21:21 UTC, eliasylonen commented
Continuing in PR #9182

2024-12-21 21:21 UTC, closed without merging