Fix : #8825 If attachment token expires, it throws a 500 error instead of Unauthenticated
twentyhq/twenty pull request #9043
Opened 2024-12-12 16:17 UTC by munch-lax

FilePathGuard implements token verification via verifyWorkspaceToken function which throws AuthException error , 
since CanActivate expects a boolean value , we add a try catch while verifying the token 

if token is invalid/expired 
<img width="1470" alt="Screenshot 2024-12-12 at 9 44 58 PM" src="https://github.com/user-attachments/assets/106a85dd-f894-46ea-80c3-f29b4ea5b4d3" />
else 
<img width="917" alt="Screenshot 2024-12-12 at 9 47 10 PM" src="https://github.com/user-attachments/assets/d82168f4-d140-48dc-94a4-56773a93db83" />

2024-12-17 19:45 UTC, charlesBochet commented on packages/twenty-server/src/engine/core-modules/file/guards/file-path-guard.ts
> +    let payload:any ={}
Please check run your linter: npx nx run twenty-server:lint

2024-12-17 19:47 UTC, charlesBochet commented on packages/twenty-server/src/engine/core-modules/file/guards/file-path-guard.ts
> +    else{
no need for else as you are already returning

if (error instance of...) {
return
}

throw ...

2024-12-17 19:49 UTC, charlesBochet commented on packages/twenty-server/src/engine/core-modules/file/guards/file-path-guard.ts
> +    else{
actually forget about this comment as I think we should have another strategy :)

2024-12-17 19:51 UTC, charlesBochet requested changes
Hi @munch-lax thanks for the PR. We would like to follow another strategy here:
1) Create a FileAPIExceptionFilter (similar to AuthRestApiExceptionFilter) this filter should be able to handle the AuthException (with  AuthExceptionCode.UNAUTHENTICATED)
2) use it on top of the file.controller.ts (see GoogleAPIsAuthController as an example)

Now the exception that is thrown in the file-path-guard will be properly handled.

2024-12-18 15:37 UTC, munch-lax commented
Hey @charlesBochet do we need to return the error in the same format that is by using handleExceptionService.handleError ?

2024-12-18 15:39 UTC, charlesBochet commented
It should be very similar to AuthRestApiExceptionFilter :) so same output format

2025-01-01 19:35 UTC, Ritzrawal requested changes

2025-01-01 19:35 UTC, Ritzrawal commented on packages/twenty-server/src/engine/core-modules/file/controllers/file.controller.ts
> +} from '@nestjs/common';
```suggestion
import {
  Get,
  Req,
  Res,
  Param,
  UseGuards,
  Controller,
  UseFilters,
} from '@nestjs/common';
```

i think arranging in this pattern make it easier to reviewing the code  and helps to increase the code quality its just a suggestion

2025-01-03 19:56 UTC, FelixMalfait commented on packages/twenty-server/src/engine/core-modules/file/controllers/file.controller.ts
> +} from '@nestjs/common';
The sorting should be done automatically via Linter rules :) (alphabetically, not by length)

2025-01-04 09:32 UTC, FelixMalfait commented
Thanks! Let's keep unauthenticated as a 403 for now to stay consistent with the rest of the codebase but I created a followup issue here https://github.com/twentyhq/twenty/issues/9347

2025-01-04 10:07 UTC, FelixMalfait commented
There's another issue with our current code which I'll fix (not linked to your PR). We've implemented a second notion of "expirationDate" just for the file service. The expiry is something JWT handle natively well and we should rely on the JWT expiry instead of introducing a second expirationDate. With the current code the file expiration date would be the lowest of the default token expiration date and the file token expiration date which doesn't make sense.

2025-01-04 12:15 UTC, FelixMalfait approved these changes
Good for me! But I'll let you check again before @charlesBochet since it can affect security

2025-01-08 17:20 UTC, charlesBochet commented
I'm back from holidays, I'm taking a look

2025-01-08 18:06 UTC, charlesBochet approved these changes

2025-01-08 18:07 UTC, charlesBochet commented
Thank you @munch-lax :) I've moved your code to a different location (file.exception.ts instead of auth.exception.ts and same for the filter)

2025-01-08 18:09 UTC, merged