Remove react hook form in send email action
twentyhq/twenty pull request #9130
Opened 2024-12-18 16:36 UTC by thomtrp

- remove react hook form
- put back multiline for body

2024-12-18 17:20 UTC, Devessier commented on packages/twenty-front/src/modules/workflow/workflow-actions/components/WorkflowEditActionFormSendEmail.tsx
> +  }, [action.settings.input]);
Honestly, I'm not sure if we need this useEffect. If the server takes time to respond, the form's state might be corrupted.

2024-12-18 17:56 UTC, Devessier requested changes
It looks good! Thank you for taking this bug. I would like us to delete the useEffect we used to synchronize the local state with the backend state. It's primarily dead code, and it's simpler not to override the local state with the backend state for now.

2024-12-18 17:56 UTC, Devessier commented on packages/twenty-front/src/modules/workflow/workflow-actions/components/WorkflowEditActionFormSendEmail.tsx
> +  }, [action.settings.input]);
After reviewing this, I would remove the useEffect. We built the form field inputs with a `defaultValue` in mind, not a `controlled` `value`. Technically, our abstractions don't allow us to set the value of TipTap editors.

This `useEffect` has no effect, at least for form fields. The connected account select is a controlled component, and this `useEffect` would set its value. I think it's better to consider that the back-end state doesn't override the local state. We'll see how we can handle it properly if that's okay with you. Preventing the local override makes the experience on a slow network better. I prefer not to override what people might have typed in inputs to display the fresher data coming from the backend.

2024-12-19 07:43 UTC, martmull approved these changes
Agree with Baptiste comment, I still approve

2024-12-19 07:43 UTC, martmull commented on packages/twenty-front/src/modules/workflow/workflow-actions/components/WorkflowEditActionFormSendEmail.tsx
> +  }, [action.settings.input]);
+1 for removing the useEffect. I agree with Baptiste on prioritizing optimistic rendering over matching the backend state. More generally, removing a useEffect aligns with the project standards.

2024-12-19 09:44 UTC, Devessier approved these changes
Nice! Thank you.

2024-12-19 09:48 UTC, merged