fix: reset table selection when navigating away from index page
twentyhq/twenty pull request #9140
Opened 2024-12-19 04:34 UTC by samyakpiya

Fixes #9132 

## Purpose
Currently, when navigating away from an index page and returning, previously checked selections remain checked. This fix ensures the selection context is properly reset on navigation.

## Changes
- Add `RecordIndexResetSelectionEffect` component to handle selection cleanup
- Integrate effect into `RecordIndexPage`
- Uses existing `useResetTableRowSelection` hook to clear selections

## Testing
1. Go to any index page (e.g., Companies)
2. Select some records using checkboxes
3. Navigate to a detail page
4. Return to the index page
5. Verify that no records are selected

## Demo
I've recorded a short video demonstrating how this PR fixes the issue:

[Loom Video Link](https://www.loom.com/share/72ca46a5dc194b5092e1944a985fa0d2?sid=55c95d8b-2376-4ac5-b406-6483aa7e341f)

Before fix: Selections persist after navigation
After fix: Selections are properly reset

2024-12-19 16:17 UTC, charlesBochet approved these changes
LGTM, thank you :)

2024-12-19 16:45 UTC, charlesBochet commented
@samyakpiya I have approved first but we actually would like to test a different pattern. We are trying to get rid of the useEffects completely on the codebase

The right way to do that is to let the caller synchronously reset the table selection. But how could the link in RecordDetailSectionHeader know that it should reset the table selection: let's introduce a <NavigateToIndexPageLink> component that will include a <Link to={...} onClick{resetTableSelection} />

2024-12-19 16:46 UTC, charlesBochet requested changes
see comment above

2024-12-19 21:32 UTC, samyakpiya commented
@charlesBochet Thanks for the feedback! I understand we want to move away from useEffect and handle the selection reset synchronously through the Link component's onClick. I'll update the PR to implement this pattern instead.

2024-12-20 01:32 UTC, samyakpiya commented
@charlesBochet I've considered the pattern you suggested but have some technical concerns to discuss.

The current suggestion to handle reset via `<Link onClick={resetTableSelection}>` would only cover the show page → index page navigation path. However, shouldn't the table selection reset whenever we leave the index page, regardless of destination? For instance:

1. Workspace switches
2. Direct URL changes (browser back/forward)
3. Navigation to any other route
4. External links

Additionally, implementing this through Links would require lifting state management up the component tree to make the reset function available to both index and show pages.

Would it make more sense to handle this at the routing/navigation level instead? This would ensure consistent behavior regardless of how the user leaves the index page. I'm happy to explore alternative patterns that don't use useEffect while still covering all these edge cases.

2024-12-27 11:27 UTC, lucasbordeau commented
@samyakpiya Let's implement an isLeavingIndexPage in PageChangeEffect, we'll refactor when we refactor PageChangeEffect.

2024-12-27 12:25 UTC, samyakpiya commented
Sounds good, thanks!

2025-01-08 04:36 UTC, samyakpiya commented
@lucasbordeau `useResetTableRowSelection(objectNamePlural)` seems to throw whenever `objectNamePlural` is an empty string because of [this](https://github.com/twentyhq/twenty/blob/4f7fa7adcdf9598c94a4806e678b48a1cc5e3da0/packages/twenty-front/src/modules/object-record/record-table/hooks/internal/useResetTableRowSelection.ts#L16C1-L19C5).

But if we're setting the reset logic in this `PageChangeEffect`, since hooks can't be called conditionally, every time the code reaches this point:

```
const resetTableSelections = useResetTableRowSelection(objectNamePlural);
```

and the user is not currently in the `RecordIndexPage`, this is bound to throw. I've currently used `CoreObjectNamePlural.Person` as a workaround, but don't think this the right way to do it. How would you handle it?

2025-01-08 04:38 UTC, samyakpiya commented on packages/twenty-front/src/modules/app/effect-components/PageChangeEffect.tsx
> +  const objectNamePlural =
@lucasbordeau `useResetTableRowSelection(objectNamePlural)` seems to throw whenever `objectNamePlural` is an empty string because of [this](https://github.com/twentyhq/twenty/blob/4f7fa7adcdf9598c94a4806e678b48a1cc5e3da0/packages/twenty-front/src/modules/object-record/record-table/hooks/internal/useResetTableRowSelection.ts#L16C1-L19C5).

But if we're setting the reset logic in this `PageChangeEffect`, since hooks can't be called conditionally, every time the code reaches this point:

```
const resetTableSelections = useResetTableRowSelection(objectNamePlural);
```

and the user is not currently in the `RecordIndexPage`, this is bound to throw. I've currently used `CoreObjectNamePlural.Person` as a workaround, but don't think this the right way to do it. How would you handle it?

2025-01-08 09:25 UTC, lucasbordeau commented on packages/twenty-front/src/modules/app/effect-components/PageChangeEffect.tsx
> +  const objectNamePlural =
This is technical debt at this point, we have to refactor this hook. 

I suggest that you add a TODO comment and let your current fix which is enough for now.

2025-01-09 12:41 UTC, lucasbordeau approved these changes

2025-01-11 10:00 UTC, charlesBochet approved these changes

2025-01-11 10:23 UTC, merged