WIP: Add Email Verification for non-Microsoft/Google Emails
twentyhq/twenty pull request #9288
Opened 2024-12-31 05:35 UTC by samyakpiya

Closes #8240 

# WIP - TODOs:

## Sign Up Process

- [x] Introduce server-level environment variable IS_EMAIL_VERIFICATION_REQUIRED (defaults to false)
- [ ] Generate an email verification token
- [ ] Store the token in appToken
- [ ] Send email containing the verification link
- [ ] Create a frontend page to handle verification requests

## Sign In Process

- [ ] After verifying user credentials, check if user's email is verified and prompt to to verify
- [ ] Show an option to resend the verification email

## Database

- [ ] Rename the `emailVerified` colum on `user` to to `isEmailVerified` for consistency

## Deployment
- [ ]  Run a script/sql query to set `isEmailVerified` to `true` for all users with a Google/Microsoft email and all users that show an indication of a valid subscription (e.g. linked credit card)

2025-01-04 15:17 UTC, samyakpiya commented
@FelixMalfait I spent way too long trying to figure out why the frontend couldn't make a mutation request without an auth token. Turns out there was middleware in place even though no auth guards were on the resolver. Probably should’ve just asked someone, lol.

Still need to rename the column to isEmailVerified, but other than that, it’s ready for review!

2025-01-04 15:34 UTC, samyakpiya commented on packages/twenty-front/src/modules/auth/components/VerifyEmail.tsx
> +      if (!emailVerificationToken) return;
User are redirected to this page upon signup (emailVerificationToken absent) but also upon clicking the verification link on their email (emailVerificationToken present). When the token is absent, this is intended behavior as oterhwise users would see an error snackbar after signup redirect.

2025-01-04 15:36 UTC, samyakpiya commented on packages/twenty-front/src/modules/auth/graphql/mutations/resendEmailVerificationToken.ts
> +    }
Might need the design for the modal that prompts user to verify email in general, but also if we want to include additional information like when the token expires.

2025-01-04 15:38 UTC, samyakpiya commented on packages/twenty-front/src/modules/auth/components/VerifyEmail.tsx
> +  }, []);
Following the pattern from `VerifyEffect.tsx`.

2025-01-04 15:44 UTC, samyakpiya commented on packages/twenty-front/src/modules/auth/hooks/useAuth.ts
> +      }
Currently, when a user enters email & password to sign up, an account gets created. It is only after account creation that the verification email gets sent. If `verify()` gets called first, it would sign in the user even if their email might not be verified.

2025-01-04 15:48 UTC, samyakpiya commented on packages/twenty-front/src/modules/auth/sign-in-up/components/SignUpEmailVerification.tsx
> +    if (!email) return;
Resolved in recent commit.

2025-01-04 15:52 UTC, samyakpiya commented on packages/twenty-front/src/modules/auth/sign-in-up/components/SignUpEmailVerification.tsx
> +    }
Resolved in recent commit.

2025-01-04 16:01 UTC, samyakpiya commented on packages/twenty-server/src/engine/core-modules/auth/auth.resolver.ts
> +    );
Resolved in recent commit.

2025-01-04 16:04 UTC, samyakpiya commented on packages/twenty-server/src/engine/core-modules/domain-manager/service/domain-manager.service.ts
> +    });
buildWorkspaceURL() uses url.set() under the hood to set the searchParams, which automatically handles URL encoding.

2025-01-04 16:07 UTC, samyakpiya commented on packages/twenty-server/src/engine/core-modules/email-verification/dtos/verify-email.output.ts
> +  email?: string;
Resolved in recent commit.

2025-01-04 16:13 UTC, samyakpiya commented on packages/twenty-server/src/engine/core-modules/email-verification/email-verification.exception.ts
> +  EMAIL_VERIFICATION_NOT_REQUIRED = 'EMAIL_VERIFICATION_NOT_REQUIRED',
@FelixMalfait Should we add rate limiting to the `verifyEmail` mutation in `email-verification.resolver.ts`? I'm thinking something like `@Throttle({ default: { ttl: 60, limit: 5 } })`?

2025-01-04 16:14 UTC, samyakpiya commented on packages/twenty-server/src/engine/core-modules/email-verification/email-verification.resolver.ts
> +    resendEmailVerificationTokenInput: ResendEmailVerificationTokenInput,
@FelixMalfait Should we add rate limiting to the verifyEmail mutation in email-verification.resolver.ts? I'm thinking something like @Throttle({ default: { ttl: 60, limit: 5 } })?

2025-01-04 16:21 UTC, samyakpiya commented on packages/twenty-server/src/engine/core-modules/email-verification/utils/cast-app-token-to-email-verification.util.ts
> +  }
This case was already handled before `castAppTokenToEmailVerification()` was called, but I'll move that logic here instead for consistency.

2025-01-04 16:22 UTC, samyakpiya commented on packages/twenty-server/src/engine/core-modules/email-verification/utils/cast-app-token-to-email-verification.util.ts
> +  }
Resolved in recent commit.

2025-01-04 16:26 UTC, samyakpiya commented on packages/twenty-front/src/modules/auth/components/VerifyEffect.tsx
> +        await verify(loginToken, email ?? '');
This was already the initial behavior.

2025-01-04 18:54 UTC, samyakpiya commented on packages/twenty-front/src/utils/isEmailFromTrustedProvider.ts
> +  return email.endsWith('@gmail.com') || email.endsWith('@outlook.com');
The previous implementation incorrectly assumed that email verification should be
skipped for @gmail.com and @outlook.com domains. However, verification should be
required based on the authentication method used (SSO vs email/password), not the
email domain.

2025-01-04 18:55 UTC, samyakpiya commented on packages/twenty-front/src/utils/isEmailFromTrustedProvider.ts
> +  return email.endsWith('@gmail.com') || email.endsWith('@outlook.com');
The previous implementation incorrectly assumed that email verification should be
skipped for @gmail.com and @outlook.com domains. However, verification should be
required based on the authentication method used (SSO vs email/password), not the
email domain.

2025-01-05 06:48 UTC, samyakpiya commented on packages/twenty-emails/src/components/Footer.tsx
> +      <Row>
Resolved in recent commit.

2025-01-05 07:18 UTC, samyakpiya commented on packages/twenty-server/src/engine/core-modules/user/services/user.service.ts
> +    user.emailVerified = true;
Resolved in recent commit.

2025-01-05 09:34 UTC, FelixMalfait commented
Wow, big piece!!! Thanks a lot!

2025-01-05 10:22 UTC, samyakpiya commented
Sure thing! I didn’t realize how much work this PR would entail when I started, but it was a great opportunity to learn more about the codebase. Let me know if I can provide any additional context to make reviewing easier.

As a follow-up, I’m considering redesigning the email verification sign-up flow. Currently, /verify-email handles both email sending and validating using searchParams, but I’m thinking of shifting the initial email send to a new added `SignInUpStep` of type `EmailVerification` on the /welcome page, leaving /verify-email to focus solely on token validation.

After generating a migration to rename `emailVerified` to `isEmailVerified` and updating the GraphQL schema for twenty-front, I noticed a mismatch in twenty-chrome-extension. I regenerated its GraphQL schema and found several outdated mutation definitions that might need a new PR to fix.

2025-01-06 05:06 UTC, samyakpiya commented
@FelixMalfait I've redesigned the email verification flow since my last comment and also made all the necessary changes to handle most of the edge cases and improve UX. Please refer to the PR description for the updated video recording and screenshots. Thanks!

2025-01-06 13:28 UTC, FelixMalfait commented on packages/twenty-server/src/engine/core-modules/email-verification/services/email-verification.service.ts
> +        EmailVerificationExceptionCode.EMAIL_VERIFICATION_NOT_REQUIRED,
Why handle this as an error? If email verification isn't require it should just pass silently no?

2025-01-06 13:31 UTC, FelixMalfait commented on packages/twenty-emails/src/components/WhatIsTwenty.tsx
> +      <Footer />
Good idea. We should probably add this to every email as a BaseFooter like the base header?

2025-01-06 13:38 UTC, FelixMalfait commented on packages/twenty-server/src/engine/core-modules/email-verification/email-verification.resolver.ts
> +    resendEmailVerificationTokenInput: ResendEmailVerificationTokenInput,
That'd be great but probably too complex to add as part of this PR, something we would want to add for other resolvers at the same time too! Right now there's a global-throttling (check useThrottler in GraphQLConfigService) and a CaptchaGuard, that's it. I guess if we wanted to add something it would probably be the captcha guard...

2025-01-06 13:41 UTC, FelixMalfait commented on packages/twenty-server/src/engine/core-modules/auth/services/sign-in-up.service.ts
> +      await this.userService.markEmailAsVerified(updatedUser.id);
Right now we don't force the user who signs up with an invitation to use the same email their were invited on so technically we can't be 100% sure that email is verified, unless we force signing up with the same email as in the invitation. I'm not sure if it's worth doing though...

2025-01-06 13:53 UTC, FelixMalfait commented on packages/twenty-front/src/modules/auth/hooks/useAuth.ts
> +        const maybeUser = await checkUserExistsQuery({
this endpoint is protected by captcha guard

2025-01-06 13:56 UTC, FelixMalfait commented on packages/twenty-front/src/modules/auth/hooks/useAuth.ts
>    const handleVerify = useCallback(
I find this pattern a bit strange. Verify should be used to exchange a login token (temporary) against an auth token pair (access token + refresh token). I haven't finished reading through the code but it feels like what you're doing here should be on the backend (for security reasons OR just to avoid duplication if you also checked isEmailVerified on the backend already))

2025-01-06 14:15 UTC, FelixMalfait commented on packages/twenty-front/src/modules/auth/sign-in-up/components/EmailVerificationSent.tsx
> +          title="Click to resend"
While I agree it'd be best to have throttling on the backend side, I guess we can implemented a small 60 seconds counter on the frontend side for now?

2025-01-06 14:15 UTC, FelixMalfait commented
Haven't had time to do a full review yet but did a few first comments. Congrats, really great work!

2025-01-06 14:17 UTC, FelixMalfait commented on packages/twenty-front/src/modules/auth/components/VerifyEmailEffect.tsx
> +  useEffect(() => {
FYI we are trying to remove all useEffect in the codebase, but OK to keep this one for now  imo if it's too complex, since it's just a copy of the implementation we have in Verify. We should make sure to remove both in the future.

2025-01-06 15:04 UTC, samyakpiya commented on packages/twenty-front/src/modules/auth/sign-in-up/components/EmailVerificationSent.tsx
> +          title="Click to resend"
While it's not exactly throttling, I did implement a kind of rate limiting:

https://github.com/twentyhq/twenty/pull/9288/commits/70726479895cc0ada21f4513c241219bf535ff19#diff-b15c641225d087df87815d188924c01eb28bd0d6a523913895a28ce829f443baR112

This follows a similar pattern to the `generatePasswordResetToken()` in `reset-password.service.ts`.

2025-01-06 15:18 UTC, samyakpiya commented on packages/twenty-emails/src/components/WhatIsTwenty.tsx
> +      <Footer />
There are some emails (as seen in Figma) that don't have footer links in them:

![alt text](<Screenshot 2025-01-06 at 10.14.35 AM.png>)

However, the Footer is already being used in all the places it was before as it's there as a default in <WhatIsTwenty/>. Should I extract it outside of it and add <Footer /> to all the places <WhatIsTwenty /> was being used?

2025-01-06 15:34 UTC, samyakpiya commented on packages/twenty-server/src/engine/core-modules/email-verification/services/email-verification.service.ts
> +        EmailVerificationExceptionCode.EMAIL_VERIFICATION_NOT_REQUIRED,
The frontend uses the same env to conditionally invoke the mutation that leads to `sendVerificationEmail()`. This made sense to me as it would avoid unnecessary calls to the backend when `IS_EMAIL_VERIFCATION_REQUIRED` is `false`.

To answer your question, I am throwing this here and in some other methods because I thought it might confuse the users if, for instance, they're trying to verify their email or resend the email verification token but it seems like it's not working (cause it's passing silently) and they don't realize the env has been reset or not set to true in the first place.

2025-01-06 15:49 UTC, samyakpiya commented on packages/twenty-server/src/engine/middlewares/graphql-hydrate-request-from-token.middleware.ts
>        'Verify',
No problem! It's wasn't intuitive what `Verify` and `Challenge` to me either when I discovered it. I'll make this change.

2025-01-06 16:00 UTC, FelixMalfait commented on packages/twenty-front/src/modules/auth/sign-in-up/components/EmailVerificationSent.tsx
> +          title="Click to resend"
Aaaah I see, I thought API-level throttling but this is better. Great!

2025-01-06 16:02 UTC, FelixMalfait commented on packages/twenty-server/src/engine/core-modules/email-verification/services/email-verification.service.ts
> +        EmailVerificationExceptionCode.EMAIL_VERIFICATION_NOT_REQUIRED,
I see! Thanks

> The frontend uses the same env to conditionally invoke the mutation that leads to sendVerificationEmail().

This is not something that you would typically do on the frontend. If you have doubts, usually the more goes in the backend the better! (because tomorrow their might be a mobile app or other frontends).

Make sure that this error isn't triggered for someone who have `IS_EMAIL_VERIFCATION_REQUIRED` set to `false`. I haven't pulled the code yet (will do), but when @Bonapara did he saw this exception (with IS_EMAIL_VERIFCATION_REQUIRED not set initially)

2025-01-06 16:16 UTC, samyakpiya commented on packages/twenty-server/src/engine/core-modules/auth/services/sign-in-up.service.ts
> +      await this.userService.markEmailAsVerified(updatedUser.id);
We actually do enforce that: 

https://github.com/twentyhq/twenty/blob/b22a598d7d1901b940ad91be47358f696d31abf9/packages/twenty-server/src/engine/core-modules/workspace-invitation/services/workspace-invitation.service.ts#L95

I verified by sending an invite to `a@a.com` and changing the sign up email to `b@b.com`. We get back an error:

![image](https://github.com/user-attachments/assets/5d89836b-723e-458c-a623-8c2e088e3672)

2025-01-06 16:26 UTC, samyakpiya commented on packages/twenty-server/src/engine/core-modules/email-verification/email-verification.resolver.ts
> +    resendEmailVerificationTokenInput: ResendEmailVerificationTokenInput,
Rate limiting on the backend has been introduced in a recent commit that I referenced in another comment above. Is it still necessary to add captcha guard here?

2025-01-06 16:30 UTC, FelixMalfait commented on packages/twenty-server/src/engine/core-modules/email-verification/email-verification.resolver.ts
> +    resendEmailVerificationTokenInput: ResendEmailVerificationTokenInput,
No you're right! 
You could argue that detecting bot is still a different issue but I think your current implementation is good enough

2025-01-06 16:42 UTC, FelixMalfait commented on packages/twenty-emails/src/components/WhatIsTwenty.tsx
> +      <Footer />
Good point. But I think we'll want a footer on every emails for consistency (e.g. one day we'll need to add "manage your preferences" button). We might edit the footer in a followup issue to make it smaller and better suited for all emails, but let's include it in all emails for now

cc @Bonapara let me know if you disagree

2025-01-06 16:49 UTC, samyakpiya commented on packages/twenty-front/src/modules/auth/hooks/useAuth.ts
> +        const maybeUser = await checkUserExistsQuery({
Is that a problem? My understanding based on this snippet is that:

https://github.com/twentyhq/twenty/blob/b22a598d7d1901b940ad91be47358f696d31abf9/packages/twenty-front/src/modules/app/effect-components/PageChangeEffect.tsx#L155C1-L164C77

since the handleVerify only ever gets called from the `AppPath.SignInUp` page, the requests made will have a valid captcha token. Is that correct?

I was actually thinking of replacing the `checkUserExistsQuery` with something like `checkUserEmailVerified`, but decided to return the `emailVerified` attribute in `checkUserExistsQuery` itself to reuse what was already existing. Do you think its okay to introduce `checkUserExistsQuery`?

2025-01-06 21:24 UTC, samyakpiya commented on packages/twenty-front/src/modules/auth/components/VerifyEmailEffect.tsx
> +        await verifyEmail(emailVerificationToken);
I see, I thought it was safer this way. I'm currently storing the raw `emailVerificationToken` in the database and the expiry is set to 1d by default. I'll instead store the hashed version and reset the expiry to 1h since users are able to resend the `emailVerificationToken` anyways.

2025-01-06 21:25 UTC, samyakpiya commented on packages/twenty-front/src/modules/auth/components/VerifyEmailEffect.tsx
> +        await verifyEmail(emailVerificationToken);
Also, greptile suggested changing some file that documents the env, but I couldn't find it.

2025-01-06 23:25 UTC, samyakpiya commented on packages/twenty-server/src/engine/middlewares/graphql-hydrate-request-from-token.middleware.ts
>        'Verify',
Should we also rename the corresponding frontend functions (challenge, verify, verifyEmail)? 

```typescript
return {
    challenge: handleChallenge,
    verify: handleVerify,
    verifyEmail: handleVerifyEmail,

    loadCurrentUser,

    checkUserExists: { checkUserExistsData, checkUserExistsQuery },
    clearSession,
    signOut: handleSignOut,
    signUpWithCredentials: handleCredentialsSignUp,
    signInWithCredentials: handleCrendentialsSignIn,
    signInWithGoogle: handleGoogleLogin,
    signInWithMicrosoft: handleMicrosoftLogin,
  };
  ```

2025-01-07 01:24 UTC, samyakpiya commented on packages/twenty-front/src/modules/auth/components/VerifyEffect.tsx
> +        await verify(loginToken, email ?? '');
Resolving here so we have one place of conversation about this (down below).

2025-01-07 03:44 UTC, samyakpiya commented on packages/twenty-front/src/modules/auth/hooks/useAuth.ts
>    const handleVerify = useCallback(
Based on this and your feedback about it being better to have more stuff in the backend, I've made the changes in my local repo that follows the above pattern you've mentioned.

Whenever authService.verify() is called in the backend, I'm adding this check:

```typescript
if (
      this.environmentService.get('IS_EMAIL_VERIFICATION_REQUIRED') &&
      !user.isEmailVerified
    ) {
      throw new AuthException(
        'Email is not verified',
        AuthExceptionCode.EMAIL_NOT_VERIFIED,
      );
    }
```
This works fine and shows the user an error when they try to login when their email is not verified. However, I also want to redirect them to resend email verification page if the error that got thrown had an exception code of `AuthException.EmailVerified`.  I didn't see any existing patterns where we were conditionally doing something on the frontend based on the exception code being sent by the backend. So, this is how I'm implementing it right now although it doesn't have type safety so leaving that as a TODO for now.

```typescript
const handleChallenge = useCallback(
    async (email: string, password: string, captchaToken?: string) => {
      try {
        const challengeResult = await challenge({
          variables: {
            email,
            password,
            captchaToken,
          },
        });
        if (isDefined(challengeResult.errors)) {
          throw challengeResult.errors;
        }

        if (!challengeResult.data?.challenge) {
          throw new Error('No login token');
        }

        return challengeResult.data.challenge;
      } catch (error) {
        // TODO: Get intellisense for graphql error extensions code (codegen?)
        if (
          error instanceof ApolloError &&
          error.graphQLErrors[0]?.extensions?.code === 'EMAIL_NOT_VERIFIED'
        ) {
          setSearchParams({ email });
          setSignInUpStep(SignInUpStep.EmailVerification);
          throw error;
        }
        throw error;
      }
    },
    [challenge, setSearchParams, setSignInUpStep],
  );
```

2025-01-07 08:14 UTC, samyakpiya commented on packages/twenty-server/src/engine/core-modules/email-verification/email-verification.exception.ts
> +}
This is in tune with existing patterns.

2025-01-07 08:15 UTC, samyakpiya commented on packages/twenty-server/src/engine/core-modules/email-verification/services/email-verification.service.ts
> +    const user = await this.userService.getUserByEmail(email);
This is handled within userService.

2025-01-07 08:16 UTC, samyakpiya commented on packages/twenty-server/src/engine/core-modules/user-workspace/user-workspace.service.ts
> +    });
Irrelevant.

2025-01-07 08:18 UTC, samyakpiya commented on packages/twenty-server/src/engine/middlewares/graphql-hydrate-request-from-token.middleware.ts
>        'Verify',
Actually, can I open up a new issue for this and have myself assigned? This PR is getting too big.

2025-01-07 08:22 UTC, samyakpiya commented on packages/twenty-front/src/modules/auth/components/VerifyEmailEffect.tsx
> +  useEffect(() => {
Could you clarify the rationale behind removing useEffect across the codebase? Also what alternative pattern or strategy are we adopting to handle side effects and lifecycle events in its place?

2025-01-07 08:27 UTC, samyakpiya commented on packages/twenty-server/src/engine/core-modules/environment/environment-variables.ts
> +  EMAIL_VERIFICATION_TOKEN_EXPIRES_IN = '1d';
This has been set to 1h in a recent commit.

2025-01-07 08:27 UTC, samyakpiya commented on packages/twenty-server/src/engine/core-modules/user-workspace/user-workspace.service.ts
> +      sso: userWorkspace.workspace.workspaceSSOIdentityProviders.reduce(
Irrelevant for now. This already existed, I just moved the method to a different service.

2025-01-07 08:29 UTC, samyakpiya commented on packages/twenty-front/src/modules/auth/components/VerifyEmail.tsx
> +        });
I couldn't find a clean way to reference the backend exception codes defined in the frontend.

2025-01-07 08:30 UTC, samyakpiya commented on packages/twenty-front/src/modules/auth/components/VerifyEmail.tsx
> +        });
I'm resolvign this as I've added this as a TODO and referenced it in a different conversation.

2025-01-07 08:30 UTC, samyakpiya commented on packages/twenty-front/src/modules/auth/components/VerifyEmail.tsx
> +      if (!emailVerificationToken) return;
Outdated, resolving.

2025-01-09 14:15 UTC, FelixMalfait commented
Finally had time to test today! 

One small thing I noticed. Will add more as I review

<img width="453" alt="Screenshot 2025-01-09 at 15 14 14" src="https://github.com/user-attachments/assets/d7233743-34d9-48d8-904c-205c5ad9a87b" />

2025-01-09 14:19 UTC, FelixMalfait commented
Other issue: if I check in prod, when I accept an invite, I'm logged in automatically after signin up. On this branch, it seems I have to re-login manually after signing up.

2025-01-09 14:20 UTC, FelixMalfait commented on packages/twenty-front/src/modules/auth/components/VerifyEmailEffect.tsx
> +  useEffect(() => {
It becomes very messy if everyone uses useEffect everywhere, you can have re-render loops that are hard to debug. Here's an article that talks about alternatives: https://react.dev/learn/you-might-not-need-an-effect

2025-01-09 14:24 UTC, FelixMalfait commented on packages/twenty-front/src/modules/auth/components/VerifyEmailEffect.tsx
> +        await verifyEmail(emailVerificationToken);
You can update `setup.mdx` in twenty-website to document the variables

I understand the security pov but I hate websites that asks you to re-login when you've just created your account, let's make sure we don't!

2025-01-09 14:39 UTC, FelixMalfait commented on packages/twenty-front/src/generated-metadata/graphql.ts
> -  IsViewGroupsEnabled = 'IsViewGroupsEnabled',
https://github.com/twentyhq/twenty/commit/b71246bc5dd54bdd48ab6f4bbc4c402f140f0d37 this was brought back under a feature flag

2025-01-09 14:43 UTC, FelixMalfait commented on packages/twenty-front/src/hooks/__tests__/usePageChangeEffectNavigateLocation.test.ts
> +  { loc: AppPath.VerifyEmail, isLoggedIn: true, subscriptionStatus: undefined, onboardingStatus: OnboardingStatus.PlanRequired, res: undefined },
Todo: make sure it behaves correctly when you're logged in to a different account. Based on the test scenarios here it doesn't redirect you anywhere if you're already logged in (which is fine imo, but let's see later in the PR if VerifyEmail handles this well)

2025-01-09 14:56 UTC, samyakpiya commented
> Other issue: if I check in prod, when I accept an invite, I'm logged in automatically after signin up. On this branch, it seems I have to re-login manually after signing up.

I can't seem to recreate this on my end, when I accept an invite and hit sign up, it logs me in automatically.

Did you pull the recent changes I made from 2 days ago (that's when I added the automatic sign in behavior)?

2025-01-09 15:04 UTC, samyakpiya commented
> Finally had time to test today!
> 
> One small thing I noticed. Will add more as I review
> 
> <img alt="Screenshot 2025-01-09 at 15 14 14" width="453" src="https://private-user-images.githubusercontent.com/6399865/401572081-d7233743-34d9-48d8-904c-205c5ad9a87b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0MzQ3MjAsIm5iZiI6MTczNjQzNDQyMCwicGF0aCI6Ii82Mzk5ODY1LzQwMTU3MjA4MS1kNzIzMzc0My0zNGQ5LTQ4ZDgtOTA0Yy0yMDVjNWFkOWE4N2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMDlUMTQ1MzQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTE5YTYxMTk0MDE3M2UwZDIzMWZiMWIxYWE5Yjc4ZWE0YjAyODU2MWFmY2UyZTAwMmZiNTMzZWQxNzk0ZGRmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.LaCGYiPC-GYGVrq9QT5J2uiNJp48B-1tMCXgj3JrXhQ">
> Edit: OK this happens because of the useEffect which run twice in development mode.
> 
> Maybe use states (if hasAttemptedVerification...)

I spent some time trying to debug this. When I turned StrictMode off, it seemed to work fine. So, I didn't give it much thought coz I was convinced this was behavior that would only happen in dev mode.

2025-01-09 15:15 UTC, FelixMalfait commented on packages/twenty-front/src/modules/ui/layout/hooks/__tests__/useShowAuthModal.test.tsx
> +  { loc: AppPath.VerifyEmail, isLogged: true, subscriptionStatus: SubscriptionStatus.Canceled, onboardingStatus: OnboardingStatus.Completed, res: false },
Are you sure about these? I felt like the behavior of VerifyEmail was independent of login or anything related to the currently logged in user

2025-01-09 15:26 UTC, FelixMalfait commented on packages/twenty-front/src/modules/auth/hooks/useAuth.ts
> +        const maybeUser = await checkUserExistsQuery({
Yes captcha guard is optional. People who self-host / the vast majority of instances don't use it. But for our cloud version app.twenty.com which is exposed we need it. We use Google recatpcha on our cloud. You can signup for free to try it
The excludedOperations are for the Auth Bearer verification but shouldn't affect captcha?

2025-01-09 15:30 UTC, samyakpiya commented on packages/twenty-front/src/modules/auth/hooks/useAuth.ts
> +        const maybeUser = await checkUserExistsQuery({
Yes, that is what I realized. I tried using Cloudflare Turnstile but was having some issues, I'll see if Google recaptcha works for me.

> The excludedOperations are for the Auth Bearer verification but shouldn't affect captcha?
Exactly, I came to the same conclusion.

2025-01-09 15:33 UTC, FelixMalfait commented on packages/twenty-front/src/modules/auth/hooks/useAuth.ts
>    const handleVerify = useCallback(
Good point for the type safety, could you please create an issue for that?
I guess the simplest thing we can do is just create a file to store shared error codes (NOT_FOUND, FORBIDDEN, EMAIL_NOT_VERIFIED, etc.) in the `twenty-shared` package

2025-01-09 15:43 UTC, FelixMalfait commented
If I've verified my email and come back to the link I get this message which is a bit confusing

<img width="940" alt="Screenshot 2025-01-09 at 16 42 24" src="https://github.com/user-attachments/assets/6ecf852a-02de-4197-b24d-a0ae7f6ff290" />

(I my case I landed on this due to the useEffect issue this time the first call finished before the second so the second popup was "email verification failed" and led me there)

2025-01-09 15:48 UTC, samyakpiya commented on packages/twenty-front/src/modules/auth/hooks/useAuth.ts
>    const handleVerify = useCallback(
Just created an issue for this: #9514

2025-01-09 16:01 UTC, samyakpiya commented on packages/twenty-front/src/modules/auth/components/VerifyEmailEffect.tsx
> +        await verifyEmail(emailVerificationToken);
Resolving this as it's been implemented in a recent commit.

2025-01-11 02:56 UTC, samyakpiya commented on packages/twenty-front/src/modules/auth/components/VerifyEmailEffect.tsx
> +  useEffect(() => {
Got it, thanks!

2025-01-11 02:58 UTC, samyakpiya commented on packages/twenty-server/src/engine/core-modules/auth/services/sign-in-up.service.ts
> +      await this.userService.markEmailAsVerified(updatedUser.id);
@FelixMalfait Are we good resolving this one?

2025-01-11 03:02 UTC, samyakpiya commented
@FelixMalfait, thank you for your review! I'm currently attending a 4-day long event from Jan 9 to Jan 12. I'll address the remaining feedback as soon as I'm back. :)

2025-01-13 08:24 UTC, AMoreaux requested changes
I just reviewed the server for now.

I’m impressed; it’s clear and well-organized.

2025-01-13 08:24 UTC, AMoreaux commented on packages/twenty-server/src/engine/core-modules/email-verification/services/email-verification.service.ts
> +      workspaces.length > 0 ? workspaces[0].subdomain : undefined;
Users could want to validate his email on an existing workspace in the multi-workspace environment. Not always the first workspace. 

To select the current workspace you can use 
```ts
    const workspace =
      await this.domainManagerService.getWorkspaceByOriginOrDefaultWorkspace(
        origin,
      );
```
Where origin come from 
```ts
@OriginHeader() origin: string,
```

You can find an example here:
https://github.com/twentyhq/twenty/blob/cd2946b670272a28eadef87cf0ec4de8341d2444/packages/twenty-server/src/engine/core-modules/user/user.resolver.ts#L76

2025-01-13 08:24 UTC, AMoreaux commented on packages/twenty-server/src/engine/core-modules/auth/auth.resolver.ts
> +    }
```suggestion
     workspaceValidator.assertIsDefinedOrThrow(
      workspace,  new AuthException(
        'Workspace not found',
        AuthExceptionCode.WORKSPACE_NOT_FOUND,
      );
    );
```

2025-01-13 08:24 UTC, AMoreaux commented on packages/twenty-server/src/engine/core-modules/auth/services/sign-in-up.service.ts
> +      await this.userService.markEmailAsVerified(updatedUser.id);
Yes for private invitations we enforce the email. For me it's ok.

2025-01-13 08:24 UTC, AMoreaux commented on packages/twenty-server/src/engine/core-modules/auth/token/services/email-verification-token.service.ts
> +      context: { email },
FYI: In the future, we will remove the context column and save the email in the payload of the JWT token.

2025-01-13 08:41 UTC, AMoreaux requested changes

2025-01-13 08:41 UTC, AMoreaux commented on packages/twenty-front/src/modules/auth/hooks/useAuth.ts
> +      const verifyResult = await handleVerify(
We will have conflict here.

Now handleVerify return nothing.

2025-01-13 08:41 UTC, AMoreaux commented on packages/twenty-front/src/modules/auth/hooks/__tests__/useAuth.test.tsx
> +      <MemoryRouter>{children}</MemoryRouter>
Why do you need MemoryRouter?

2025-01-13 09:24 UTC, FelixMalfait commented
I see conflicts growing 😅. Lets aim to merge this early this week!

2025-01-14 11:33 UTC, FelixMalfait commented
Let's aim to merge it this week at least before we have more conflicts. @samyakpiya would it be possible on your side to take into account the feedback in the following days?

2025-01-14 18:08 UTC, samyakpiya commented on packages/twenty-emails/src/components/WhatIsTwenty.tsx
> +      <Footer />
Opened #9622 for this. Resolving this conversation.

2025-01-14 18:09 UTC, samyakpiya commented on packages/twenty-server/src/engine/core-modules/auth/services/sign-in-up.service.ts
> +      await this.userService.markEmailAsVerified(updatedUser.id);
Sounds good, resolving this conversation.

2025-01-14 18:15 UTC, samyakpiya commented on packages/twenty-server/src/engine/middlewares/graphql-hydrate-request-from-token.middleware.ts
>        'Verify',
Resolving this as it is addressed by Issue #9623 that I opened.

2025-01-14 18:38 UTC, samyakpiya commented on packages/twenty-front/src/modules/auth/hooks/useAuth.ts
> +      const verifyResult = await handleVerify(
Resolving as a recent commit fixes this.

2025-01-14 18:45 UTC, samyakpiya commented on packages/twenty-front/src/modules/auth/hooks/__tests__/useAuth.test.tsx
> +      <MemoryRouter>{children}</MemoryRouter>
The `MemoryRouter` is required here because we recently introduced `useSearchParams` in the `useAuth` hook. Like other React Router hooks, `useSearchParams` needs to be wrapped in a Router context to function properly. Without `MemoryRouter`, the test fails with the error "useLocation() may be used only in the context of a <Router> component" since `useSearchParams` internally depends on `useLocation`.

2025-01-14 18:50 UTC, samyakpiya commented on packages/twenty-server/src/engine/core-modules/auth/auth.resolver.ts
> +    }
Resolving as I've implemented this in a recent commit.

2025-01-14 18:51 UTC, samyakpiya commented on packages/twenty-server/src/engine/core-modules/auth/token/services/email-verification-token.service.ts
> +      context: { email },
Thanks for letting me know!

2025-01-14 19:24 UTC, samyakpiya commented on packages/twenty-server/src/engine/core-modules/email-verification/services/email-verification.service.ts
> +      workspaces.length > 0 ? workspaces[0].subdomain : undefined;
Makes sense. I've made a commit that addresses this. Resolving this here.

2025-01-15 02:27 UTC, samyakpiya commented on packages/twenty-front/src/hooks/__tests__/usePageChangeEffectNavigateLocation.test.ts
> +  { loc: AppPath.VerifyEmail, isLoggedIn: true, subscriptionStatus: undefined, onboardingStatus: OnboardingStatus.PlanRequired, res: undefined },
I’ve just pushed a commit where `VerifyEmail` now replicates the behavior of `PasswordReset. Specifically, it displays the authentication modal when the user is logged in. (Refer to the screenshot below for details.)

## Key Updates

- **File Updated:** `useShowAuthModal.ts`
- **Notes:**
  - If a user is logged into **Workspace A** but clicks a verification link for **Workspace B**, they will be redirected to **Workspace B** and continue from the Onboarding flow.
  - If a user is already logged into **Workspace A** (where their email is verified) and tries to access the `VerifyEmail` page, they will encounter the following screen:

![image](https://github.com/user-attachments/assets/092e1a4c-7470-454e-9052-d8da5d45c73a)

---
@FelixMalfait Could you resolve this conversation if this behavior is fine? Thanks!

2025-01-15 02:37 UTC, samyakpiya commented on packages/twenty-front/src/modules/ui/layout/hooks/__tests__/useShowAuthModal.test.tsx
> +  { loc: AppPath.VerifyEmail, isLogged: true, subscriptionStatus: SubscriptionStatus.Canceled, onboardingStatus: OnboardingStatus.Completed, res: false },
Good catch, you're absolutely right! I've fixed this in a recent commit. 

Please resolve this once you see it. Thanks!

2025-01-15 02:45 UTC, samyakpiya commented on packages/twenty-server/src/engine/core-modules/email-verification/services/email-verification.service.ts
> +        EmailVerificationExceptionCode.EMAIL_VERIFICATION_NOT_REQUIRED,
Resolving this since it is now handled silently.

2025-01-15 02:48 UTC, samyakpiya commented on packages/twenty-server/src/engine/core-modules/email-verification/services/email-verification.service.ts
> +    if (!appToken || new Date() > appToken.expiresAt) {
Implemented.

2025-01-15 02:49 UTC, samyakpiya commented on packages/twenty-server/src/engine/core-modules/email-verification/dtos/verify-email.input.ts
> +  emailVerificationToken: string;
Added.

2025-01-15 02:52 UTC, samyakpiya commented on packages/twenty-server/src/engine/core-modules/auth/dto/user-exists.entity.ts
> +  emailVerified: boolean;
Irrelevant since if a user exists their email verified attribute could be `true` or `false`.

2025-01-15 02:53 UTC, samyakpiya commented on packages/twenty-server/src/engine/core-modules/auth/auth.module.ts
> +    EmailVerificationService,
Fixed.

2025-01-15 02:54 UTC, samyakpiya commented on packages/twenty-front/src/modules/auth/sign-in-up/components/SignUpEmailVerification.tsx
> +      });
Outdated. Email is now a required string.

2025-01-15 03:12 UTC, samyakpiya commented on packages/twenty-front/src/modules/auth/sign-in-up/components/SignUpEmailVerification.tsx
> +            : `We sent an email to ${email}. Please click the link to verify your account and continue.`}
Resolving since email is now a required string.

2025-01-15 03:13 UTC, samyakpiya commented on packages/twenty-front/src/modules/auth/hooks/useAuth.ts
> +      }
Resolving since this is outdated.

2025-01-15 03:40 UTC, samyakpiya commented on packages/twenty-front/src/modules/auth/components/VerifyEmailEffect.tsx
> +  useEffect(() => {
![image](https://github.com/user-attachments/assets/22ba72a0-3836-4e7a-8a18-8b8d8b5a580c)

@FelixMalfait I've tried including adding a guard in useEffect, minimizing dependencies, and checking for duplicate renders or snackbar triggers in other components. 

Despite this, the issue of duplicate snackbars persists and seems to only occur in development mode when Strict Mode is active. Is it fine to leave this behavior as is for now?

2025-01-15 03:56 UTC, samyakpiya commented
@FelixMalfait @AMoreaux I've made all the necessary changes based on feedback. Could you go through the unresolved conversations I've responded to and resolve them or let me know if further changes are needed? Thanks!

2025-01-15 08:45 UTC, FelixMalfait commented on packages/twenty-front/src/modules/auth/components/VerifyEmailEffect.tsx
> +  useEffect(() => {
Hey, no it's not acceptable - we need to find an other solution

2025-01-15 09:17 UTC, AMoreaux commented on packages/twenty-front/src/modules/auth/components/VerifyEmailEffect.tsx
> +  useEffect(() => {
It will not happen in prod env. It's expected in dev env with strict mode enable.

Check the note here: https://react.dev/reference/react/StrictMode

2025-01-15 09:26 UTC, FelixMalfait commented on packages/twenty-front/src/modules/auth/components/VerifyEmailEffect.tsx
> +  useEffect(() => {
@AMoreaux yes agree but it's not an acceptable behavior in dev env. It means there's a code smell / we shouldn't rely on useEffect here

2025-01-15 14:19 UTC, samyakpiya commented on packages/twenty-front/src/modules/ui/feedback/snack-bar-manager/hooks/useSnackBar.ts
> +          if (
Ah, this makes sense now! I didn't realize the issue was rooted at the snackbar level. I've been banging my head trying to implement workarounds: avoiding useEffect, steering clear of useRef for state, and adding guards. Thanks for catching this!

2025-01-15 14:21 UTC, AMoreaux approved these changes

2025-01-15 14:22 UTC, samyakpiya commented on packages/twenty-front/src/modules/ui/feedback/snack-bar-manager/hooks/useSnackBar.ts
> +            isDefined(newValue.dedupeKey) &&
Ah, this makes sense now! I didn't realize the issue was rooted at the snackbar level. I've been banging my head trying to implement workarounds: avoiding useEffect, steering clear of useRef for state, and adding guards. Thanks for catching this!

2025-01-15 14:55 UTC, FelixMalfait commented on packages/twenty-front/src/modules/ui/feedback/snack-bar-manager/hooks/useSnackBar.ts
> +            isDefined(newValue.dedupeKey) &&
Yes sorry I think we led you in the wrong direction. Initial loading is probably the only case where we'll keep useEffects ; in that case we want this to be done at a high level (page level), not in sub-components.
Solving the double notification at the snackbar level was probably the cleanest way to make it more idempotent in strict mode, even though it's not perfect either

2025-01-15 17:43 UTC, merged

2025-01-15 17:56 UTC, samyakpiya commented
@AMoreaux Sweet, thank you! 😄